"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { DataQualityBadge, FreshnessIndicator, ReportMetricCard, ReportsEmptyState, ReportsErrorState, ReportsHeader, ReportsPage, ReportsSessionSummary, ReportsSummary, ReportsTable, type ReportTableColumnPresentation } from "@/components/reports-ui"
import { DashboardWidget, DashboardWidgetHeader } from "@/components/dashboard-ui"
import type { PosSessionHistoryModel, PosSessionReportsViewModel, PosSessionValidationModel } from "./pos-session-reports-view-model"

const HISTORY_COLUMNS: ReportTableColumnPresentation<PosSessionHistoryModel>[] = [
  { id: "reference", header: "Session", cell: (row) => row.reference }, { id: "schedule", header: "Ouverture / fermeture", cell: (row) => row.schedule },
  { id: "activity", header: "Activité", cell: (row) => row.ordersAndVariance }, { id: "total", header: "Total", cell: (row) => row.total, align: "right", numeric: true },
  { id: "status", header: "Statut", cell: (row) => row.status },
]
export interface PosSessionReportsViewProps { model: PosSessionReportsViewModel; errors?: string[]; sessionControl: React.ReactNode; dialogs?: React.ReactNode; canValidate: boolean; saving: boolean; onValidate: (id: string) => void }
export function PosSessionReportsView({ canValidate, dialogs, errors = [], model, onValidate, saving, sessionControl }: PosSessionReportsViewProps) {
  const report = model.report
  const historyUnavailable = errors.includes("historique personnel")
  const validationsUnavailable = errors.includes("sessions à valider")
  return <ReportsPage width="reading"><ReportsHeader title="Rapports de sessions" subtitle="Consultez la session active, les encaissements, les écarts et l’historique de caisse." meta="Historique limité aux 50 sessions chargées par les requêtes existantes." context={<><DataQualityBadge quality={errors.length ? "unavailable" : model.historyQuality} label={errors.length ? "Données partiellement indisponibles" : "Historique limité à 50"} /><FreshnessIndicator freshness={errors.length ? "unknown" : "live"} label={errors.length ? "Fraîcheur partiellement indisponible" : undefined} /></>} />
    {errors.length ? <ReportsErrorState title="Certaines données de session sont indisponibles" description={`Domaines concernés : ${errors.join(", ")}. Les autres informations restent accessibles.`} /> : null}
    <div className="grid grid-cols-1 gap-[var(--dashboard-grid-gap)] lg:grid-cols-2"><div>{sessionControl}</div><DashboardWidget><DashboardWidgetHeader title="Historique des sessions" description="Une session clôturée ne disparaît jamais." /><div className="p-4"><ReportsTable label="Historique des sessions" caption="Historique des 50 dernières sessions chargées" columns={HISTORY_COLUMNS} rows={model.history} getRowKey={(row) => row.id} density="compact" errorState={historyUnavailable ? <ReportsErrorState title="Historique personnel indisponible" description="Les sessions historiques n’ont pas pu être chargées." /> : undefined} emptyState={<ReportsEmptyState title="Aucune session" description="L’historique apparaîtra après la première ouverture." />} /></div></DashboardWidget></div>
    {report ? <section aria-labelledby="pos-session-summary" className="space-y-3"><h2 id="pos-session-summary" className="sr-only">Résumé de session</h2><ReportsSessionSummary session={<span className="block">{report.reference}</span>} user={<span className="block">Employé : {report.employee}</span>} schedule={<span className="block">{report.schedule}</span>} sales={<><SessionMetric label="Résumé" value={report.status} /><SessionMetric label="Ventes" value={report.orders} /><SessionMetric label="Paiements" value={report.payments} /><SessionMetric label="Employé" value={report.employee} /></>} cash={<SessionMetric label="Espèces" value={report.cash} />} mobileMoney={<SessionMetric label="Mobile Money" value={report.mobileMoney} />} cancellations={<SessionMetric label="Heure d’ouverture" value={report.openedAt} />} discounts={<SessionMetric label="Heure de fermeture" value={report.closedAt} />} variances={<><SessionMetric label="Écarts" value={report.variance} /><SessionMetric label="Durée" value={report.duration} /></>} /></section> : <ReportsEmptyState title="Rapport indisponible" description="Le rapport sera disponible avec les données de session." />}
    {canValidate ? <DashboardWidget><DashboardWidgetHeader title="Validation des caisses" description="Comparer le réel et le système avant validation manager." /><div className="grid gap-3 p-4 lg:grid-cols-2">{validationsUnavailable ? <ReportsErrorState title="Sessions à valider indisponibles" description="La liste de validation n’a pas pu être chargée ; aucune action n’est proposée." /> : <>{model.validations.map((item) => <ValidationCard key={item.id} item={item} saving={saving} onValidate={onValidate} />)}{!model.validations.length ? <ReportsEmptyState title="Aucune caisse à valider" /> : null}</>}</div></DashboardWidget> : null}
    {dialogs}
  </ReportsPage>
}
function SessionMetric({ label, value }: { label: string; value: React.ReactNode }) { return <ReportMetricCard label={label} value={value} quality="complete" className="h-full" /> }
function ValidationCard({ item, onValidate, saving }: { item: PosSessionValidationModel; saving: boolean; onValidate: (id: string) => void }) { return <article className="grid gap-3 rounded-[var(--radius-dashboard-widget)] border border-[var(--reports-border)] p-4"><ReportsSummary className="sm:grid-cols-2 xl:grid-cols-2"><ReportMetricCard label="Commandes" value={item.orders} /><ReportMetricCard label="Système" value={item.system.replace(" FCFA", "")} unit="FCFA" /><ReportMetricCard label="Réel" value={item.real.replace(" FCFA", "")} unit="FCFA" /><ReportMetricCard label="Écart" value={item.variance.replace(" FCFA", "")} unit="FCFA" /></ReportsSummary><Button className="min-h-11" disabled={saving || item.validated} onClick={() => onValidate(item.id)}>{item.validated ? "Validée" : `Valider ${item.reference}`}</Button></article> }
