"use client"

import * as React from "react"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

export interface SettingsConfirmationDialogProps { open: boolean; onOpenChange: (open: boolean) => void; title: React.ReactNode; description: React.ReactNode; consequence?: React.ReactNode; confirmationText?: string; confirmationValue?: string; onConfirmationValueChange?: (value: string) => void; cancelLabel?: React.ReactNode; confirmLabel?: React.ReactNode; onConfirm?: () => void; loading?: boolean; destructive?: boolean; confirmDisabled?: boolean }
export function SettingsConfirmationDialog({ cancelLabel = "Annuler", confirmDisabled, confirmationText, confirmationValue = "", consequence, destructive = true, description, loading, onConfirm, onConfirmationValueChange, onOpenChange, open, confirmLabel = "Confirmer", title }: SettingsConfirmationDialogProps) { const id = React.useId(); const textMatches = !confirmationText || confirmationValue === confirmationText; return <AlertDialog open={open} onOpenChange={onOpenChange}><AlertDialogContent className="max-h-[calc(100dvh-var(--safe-top,0px)-var(--safe-bottom,0px)-1rem)] overflow-y-auto rounded-[var(--radius-dashboard-overlay)] border-[var(--settings-danger-border)] bg-[var(--settings-elevated)] shadow-[var(--shadow-dashboard-overlay)] motion-reduce:animate-none"><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader>{consequence ? <div className="rounded-[var(--radius-dashboard-input)] bg-[var(--settings-danger-surface)] p-3 text-sm text-[var(--dashboard-subtitle)]"><strong className="block text-[var(--settings-state-danger-fg)]">Conséquence</strong>{consequence}</div> : null}{confirmationText ? <div className="space-y-1.5"><Label htmlFor={id}>Saisissez « {confirmationText} » pour confirmer</Label><Input id={id} value={confirmationValue} onChange={(event) => onConfirmationValueChange?.(event.target.value)} autoComplete="off" className="min-h-11"/></div> : null}<AlertDialogFooter><AlertDialogCancel disabled={loading} className="min-h-11">{cancelLabel}</AlertDialogCancel><AlertDialogAction onClick={(event) => { event.preventDefault(); onConfirm?.() }} disabled={loading || confirmDisabled || !textMatches} aria-busy={loading || undefined} className={cn("min-h-11", destructive && "bg-destructive text-destructive-foreground hover:bg-destructive/90")}>{loading ? "Traitement…" : confirmLabel}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> }
