"use client"

import * as React from "react"
import { DashboardTableContainer } from "@/components/dashboard-ui"
import { Checkbox } from "@/components/ui/checkbox"
import { cn } from "@/lib/utils"
import type { SettingsPermissionPresentation, SettingsRolePresentation, SettingsTeamMemberPresentation } from "./settings-foundations"

export interface SettingsTeamColumn { id: string; header: React.ReactNode; render: (member: SettingsTeamMemberPresentation) => React.ReactNode; className?: string }
export interface SettingsTeamTableProps extends React.HTMLAttributes<HTMLDivElement> { members: SettingsTeamMemberPresentation[]; columns: SettingsTeamColumn[]; loading?: boolean; empty?: React.ReactNode; error?: React.ReactNode; actions?: React.ReactNode; caption: string }
export const SettingsTeamTable = React.forwardRef<HTMLDivElement, SettingsTeamTableProps>(({ actions, caption, className, columns, empty, error, loading, members, ...props }, ref) => <div ref={ref} className={cn("space-y-3", className)} {...props}>{actions ? <div className="flex flex-wrap justify-end gap-2 [&_button]:min-h-11">{actions}</div> : null}{error ? <div role="alert" className="text-sm text-[var(--settings-field-error)]">{error}</div> : null}{loading ? <p role="status" className="p-4 text-sm text-[var(--settings-muted)]">Chargement de l'équipe</p> : members.length === 0 ? empty : <DashboardTableContainer label={caption}><table><caption className="sr-only">{caption}</caption><thead><tr>{columns.map((column) => <th key={column.id} scope="col" className={cn("px-4 py-3", column.className)}>{column.header}</th>)}</tr></thead><tbody className="divide-y divide-[var(--settings-divider)]">{members.map((member) => <tr key={member.id}>{columns.map((column) => <td key={column.id} className={cn("px-4 py-3", column.className)}>{column.render(member)}</td>)}</tr>)}</tbody></table></DashboardTableContainer>}</div>)
SettingsTeamTable.displayName = "SettingsTeamTable"

export interface SettingsTeamMemberCardProps extends React.HTMLAttributes<HTMLElement> { member: SettingsTeamMemberPresentation }
export const SettingsTeamMemberCard = React.forwardRef<HTMLElement, SettingsTeamMemberCardProps>(({ className, member, ...props }, ref) => <article ref={ref} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--settings-border)] bg-[var(--settings-panel)] p-4", className)} {...props}><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-sm font-semibold">{member.name}</h3>{member.email ? <p className="mt-0.5 break-all text-xs text-[var(--settings-muted)]">{member.email}</p> : null}</div>{member.status}</div>{member.role ? <div className="mt-2 text-sm">{member.role}</div> : null}{member.actions ? <div className="mt-4 flex flex-wrap gap-2 [&_button]:min-h-11">{member.actions}</div> : null}</article>)
SettingsTeamMemberCard.displayName = "SettingsTeamMemberCard"

export interface SettingsRoleMatrixProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> { roles: SettingsRolePresentation[]; permissions: SettingsPermissionPresentation[]; values: Record<string, Record<string, boolean>>; onChange?: (roleId: string, permissionId: string, value: boolean) => void; readOnly?: boolean; loading?: boolean; caption?: string }
export const SettingsRoleMatrix = React.forwardRef<HTMLDivElement, SettingsRoleMatrixProps>(({ caption = "Matrice des rôles et permissions", className, loading, onChange, permissions, readOnly, roles, values, ...props }, ref) => <div ref={ref} aria-busy={loading || undefined} className={className} {...props}>{loading ? <p role="status" className="p-4 text-sm text-[var(--settings-muted)]">Chargement de la matrice</p> : <DashboardTableContainer label={caption}><table><caption className="sr-only">{caption}</caption><thead><tr><th scope="col" className="px-4 py-3">Permission</th>{roles.map((role) => <th key={role.id} scope="col" className="px-4 py-3">{role.label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--settings-divider)]">{permissions.map((permission) => <tr key={permission.id}><th scope="row" className="px-4 py-3 text-left"><span className="block text-sm font-medium">{permission.label}</span>{permission.description ? <span className="block text-xs font-normal text-[var(--settings-muted)]">{permission.description}</span> : null}</th>{roles.map((role) => { const id = `${role.id}-${permission.id}`; return <td key={role.id} className="px-4 py-3 text-center"><Checkbox id={id} checked={Boolean(values[role.id]?.[permission.id])} disabled={readOnly} onCheckedChange={(checked) => onChange?.(role.id, permission.id, checked === true)} aria-label={`${String(role.label)} — ${String(permission.label)}`}/></td> })}</tr>)}</tbody></table></DashboardTableContainer>}</div>)
SettingsRoleMatrix.displayName = "SettingsRoleMatrix"
