"use client"

import * as React from "react"
import { Loader2 } from "lucide-react"
import { Switch } from "@/components/ui/switch"
import { cn } from "@/lib/utils"
import type { SettingsPaymentMethodPresentation } from "./settings-foundations"

export interface SettingsPaymentMethodCardProps extends Omit<React.HTMLAttributes<HTMLElement>, "name">, Omit<SettingsPaymentMethodPresentation, "id"> {}
export const SettingsPaymentMethodCard = React.forwardRef<HTMLElement, SettingsPaymentMethodCardProps>(({ actions, className, description, disabled, enabled, loading, logo, maskedIdentifier, name, onEnabledChange, order, provider, status, ...props }, ref) => { const switchId = React.useId(); return <article ref={ref} aria-busy={loading || undefined} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--settings-border)] bg-[var(--settings-panel)] p-4", disabled && "opacity-60", className)} {...props}><div className="flex min-w-0 items-start gap-3">{logo ? <span aria-hidden="true" className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-[var(--radius-dashboard-input)] bg-[var(--settings-section)]">{logo}</span> : null}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-sm font-semibold">{name}</h3>{provider ? <p className="text-xs text-[var(--settings-muted)]">{provider}</p> : null}</div>{status}</div>{description ? <div className="mt-2 text-xs leading-4 text-[var(--settings-muted)]">{description}</div> : null}{maskedIdentifier ? <p className="mt-2 break-all font-mono text-xs">{maskedIdentifier}</p> : null}{order !== undefined ? <p className="mt-2 text-xs text-[var(--settings-muted)]">Ordre : {order}</p> : null}</div></div>{enabled !== undefined && onEnabledChange ? <div className="mt-3 flex min-h-11 items-center gap-3"><Switch id={switchId} checked={enabled} onCheckedChange={onEnabledChange} disabled={disabled || loading}/><label htmlFor={switchId} className="text-sm font-medium">{enabled ? "Activé" : "Désactivé"}</label></div> : null}{loading ? <p role="status" className="mt-3 flex items-center gap-2 text-xs text-[var(--settings-muted)]"><Loader2 aria-hidden="true" className="size-4 animate-spin motion-reduce:animate-none"/>Mise à jour en cours</p> : null}{actions ? <div className="mt-4 flex flex-wrap gap-2 border-t border-[var(--settings-divider)] pt-3 [&_button]:min-h-11">{actions}</div> : null}</article> })
SettingsPaymentMethodCard.displayName = "SettingsPaymentMethodCard"

export interface SettingsPaymentMethodsProps extends React.HTMLAttributes<HTMLDivElement> { methods: SettingsPaymentMethodPresentation[]; loading?: boolean; emptyState?: React.ReactNode; error?: React.ReactNode }
export const SettingsPaymentMethods = React.forwardRef<HTMLDivElement, SettingsPaymentMethodsProps>(({ className, emptyState, error, loading, methods, ...props }, ref) => <div ref={ref} aria-busy={loading || undefined} className={cn("grid gap-3 md:grid-cols-2", className)} {...props}>{error ? <div role="alert" className="md:col-span-2 text-sm text-[var(--settings-field-error)]">{error}</div> : null}{loading ? <p role="status" className="md:col-span-2 text-sm text-[var(--settings-muted)]">Chargement des moyens de paiement</p> : methods.length ? methods.map(({ id, ...method }) => <SettingsPaymentMethodCard key={id} {...method}/>) : emptyState}</div>)
SettingsPaymentMethods.displayName = "SettingsPaymentMethods"
