"use client"

import * as React from "react"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"

type FieldFrameProps = { id?: string; label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; required?: boolean; className?: string; children: (ids: { id: string; describedBy?: string }) => React.ReactNode }
function FieldFrame({ children, className, description, error, id: providedId, label, required }: FieldFrameProps) { const generatedId = React.useId(); const id = providedId ?? generatedId; const descriptionId = description ? `${id}-description` : undefined; const errorId = error ? `${id}-error` : undefined; const describedBy = [descriptionId, errorId].filter(Boolean).join(" ") || undefined; return <div className={cn("min-w-0 space-y-1.5", className)}><Label htmlFor={id} className="text-sm font-medium">{label}{required ? <span aria-hidden="true" className="ml-1 text-[var(--data-negative)]">*</span> : null}</Label>{children({ id, describedBy })}{description ? <p id={descriptionId} className="text-xs leading-4 text-[var(--settings-muted)]">{description}</p> : null}{error ? <p id={errorId} role="alert" className="text-xs font-medium leading-4 text-[var(--settings-field-error)]">{error}</p> : null}</div> }

export interface SettingsTextFieldProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "prefix"> { label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; prefix?: React.ReactNode; suffix?: React.ReactNode; containerClassName?: string }
export const SettingsTextField = React.forwardRef<HTMLInputElement, SettingsTextFieldProps>(({ className, containerClassName, description, error, id, label, prefix, required, suffix, ...props }, ref) => <FieldFrame id={id} label={label} description={description} error={error} required={required} className={containerClassName}>{({ id: fieldId, describedBy }) => <div className="relative">{prefix ? <span className="pointer-events-none absolute inset-y-0 left-3 flex items-center text-sm text-[var(--settings-muted)]">{prefix}</span> : null}<Input ref={ref} id={fieldId} required={required} aria-required={required || undefined} aria-invalid={Boolean(error)} aria-describedby={describedBy} className={cn("min-h-11 rounded-[var(--radius-dashboard-input)] bg-[var(--settings-field-default)] focus-visible:ring-[var(--settings-field-focus)]", prefix && "pl-9", suffix && "pr-9", className)} {...props}/>{suffix ? <span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-sm text-[var(--settings-muted)]">{suffix}</span> : null}</div>}</FieldFrame>)
SettingsTextField.displayName = "SettingsTextField"

export type SettingsNumberFieldProps = Omit<SettingsTextFieldProps, "type">; export const SettingsNumberField = React.forwardRef<HTMLInputElement, SettingsNumberFieldProps>((props, ref) => <SettingsTextField ref={ref} type="number" inputMode="decimal" {...props}/>); SettingsNumberField.displayName = "SettingsNumberField"
export type SettingsUrlFieldProps = Omit<SettingsTextFieldProps, "type">; export const SettingsUrlField = React.forwardRef<HTMLInputElement, SettingsUrlFieldProps>((props, ref) => <SettingsTextField ref={ref} type="url" inputMode="url" {...props}/>); SettingsUrlField.displayName = "SettingsUrlField"

export interface SettingsTextAreaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> { label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; containerClassName?: string }
export const SettingsTextArea = React.forwardRef<HTMLTextAreaElement, SettingsTextAreaProps>(({ className, containerClassName, description, error, id, label, required, ...props }, ref) => <FieldFrame id={id} label={label} description={description} error={error} required={required} className={containerClassName}>{({ id: fieldId, describedBy }) => <Textarea ref={ref} id={fieldId} required={required} aria-required={required || undefined} aria-invalid={Boolean(error)} aria-describedby={describedBy} className={cn("min-h-28 rounded-[var(--radius-dashboard-input)] bg-[var(--settings-field-default)] focus-visible:ring-[var(--settings-field-focus)]", className)} {...props}/>}</FieldFrame>)
SettingsTextArea.displayName = "SettingsTextArea"

export interface SettingsSelectOption { value: string; label: React.ReactNode; disabled?: boolean }
export interface SettingsSelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> { label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; options: SettingsSelectOption[]; placeholder?: string; containerClassName?: string }
export const SettingsSelect = React.forwardRef<HTMLSelectElement, SettingsSelectProps>(({ className, containerClassName, description, error, id, label, options, placeholder, required, ...props }, ref) => <FieldFrame id={id} label={label} description={description} error={error} required={required} className={containerClassName}>{({ id: fieldId, describedBy }) => <select ref={ref} id={fieldId} required={required} aria-required={required || undefined} aria-invalid={Boolean(error)} aria-describedby={describedBy} className={cn("dashboard-focus-visible min-h-11 w-full rounded-[var(--radius-dashboard-input)] border border-[var(--settings-border)] bg-[var(--settings-field-default)] px-3 text-sm disabled:bg-[var(--settings-field-disabled)]", className)} {...props}>{placeholder ? <option value="">{placeholder}</option> : null}{options.map((option) => <option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select>}</FieldFrame>)
SettingsSelect.displayName = "SettingsSelect"

type ToggleFrameProps = { id?: string; label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; disabled?: boolean; className?: string; control: (id: string, describedBy?: string) => React.ReactNode }
function ToggleFrame({ className, control, description, disabled, error, id: providedId, label }: ToggleFrameProps) { const generatedId = React.useId(); const id = providedId ?? generatedId; const descId = description ? `${id}-description` : undefined; const errorId = error ? `${id}-error` : undefined; const describedBy = [descId, errorId].filter(Boolean).join(" ") || undefined; return <div className={cn("flex min-h-11 items-start gap-3", disabled && "opacity-60", className)}>{control(id, describedBy)}<div className="min-w-0"><Label htmlFor={id} className="text-sm font-medium">{label}</Label>{description ? <p id={descId} className="mt-0.5 text-xs leading-4 text-[var(--settings-muted)]">{description}</p> : null}{error ? <p id={errorId} role="alert" className="mt-0.5 text-xs text-[var(--settings-field-error)]">{error}</p> : null}</div></div> }

export interface SettingsSwitchProps { id?: string; label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; checked: boolean; onCheckedChange?: (checked: boolean) => void; disabled?: boolean; readOnly?: boolean; className?: string }
export function SettingsSwitch({ checked, className, description, disabled, error, id, label, onCheckedChange, readOnly }: SettingsSwitchProps) { return <ToggleFrame id={id} label={label} description={description} error={error} disabled={disabled || readOnly} className={className} control={(controlId, describedBy) => <Switch id={controlId} checked={checked} onCheckedChange={readOnly ? undefined : onCheckedChange} disabled={disabled || readOnly} aria-invalid={Boolean(error)} aria-describedby={describedBy} className="mt-0.5"/>}/> }

export interface SettingsCheckboxProps { id?: string; label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; checked: boolean | "indeterminate"; onCheckedChange?: (checked: boolean | "indeterminate") => void; disabled?: boolean; readOnly?: boolean; className?: string }
export function SettingsCheckbox({ checked, className, description, disabled, error, id, label, onCheckedChange, readOnly }: SettingsCheckboxProps) { return <ToggleFrame id={id} label={label} description={description} error={error} disabled={disabled || readOnly} className={className} control={(controlId, describedBy) => <Checkbox id={controlId} checked={checked} onCheckedChange={readOnly ? undefined : onCheckedChange} disabled={disabled || readOnly} aria-invalid={Boolean(error)} aria-describedby={describedBy} className="mt-0.5"/>}/> }

export interface SettingsRadioOption { id: string; label: React.ReactNode; description?: React.ReactNode; disabled?: boolean }
export interface SettingsRadioGroupProps { label: React.ReactNode; description?: React.ReactNode; error?: React.ReactNode; value?: string; onValueChange?: (value: string) => void; options: SettingsRadioOption[]; disabled?: boolean; required?: boolean; className?: string }
export function SettingsRadioGroup({ className, description, disabled, error, label, onValueChange, options, required, value }: SettingsRadioGroupProps) { const id = React.useId(); const descId = description ? `${id}-description` : undefined; const errorId = error ? `${id}-error` : undefined; return <fieldset className={cn("space-y-2", className)}><legend className="text-sm font-medium">{label}{required ? <span aria-hidden="true" className="ml-1 text-[var(--data-negative)]">*</span> : null}</legend>{description ? <p id={descId} className="text-xs text-[var(--settings-muted)]">{description}</p> : null}<RadioGroup value={value} onValueChange={onValueChange} disabled={disabled} required={required} aria-describedby={[descId, errorId].filter(Boolean).join(" ") || undefined} aria-invalid={Boolean(error)}>{options.map((option) => <label key={option.id} className="flex min-h-11 items-start gap-3 rounded-[var(--radius-dashboard-input)] border border-[var(--settings-border)] p-3"><RadioGroupItem value={option.id} disabled={option.disabled} className="mt-0.5"/><span><span className="block text-sm font-medium">{option.label}</span>{option.description ? <span className="mt-0.5 block text-xs text-[var(--settings-muted)]">{option.description}</span> : null}</span></label>)}</RadioGroup>{error ? <p id={errorId} role="alert" className="text-xs text-[var(--settings-field-error)]">{error}</p> : null}</fieldset> }
