import * as React from "react"
import { ShieldAlert } from "lucide-react"
import { DashboardAlert } from "@/components/dashboard-ui"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import type { SettingsActionPresentation, SettingsDangerLevel, SettingsPermissionState, SettingsSecurityState } from "./settings-foundations"

export interface SettingsPermissionNoticeProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> { state: Exclude<SettingsPermissionState, "editable" | "hidden"> | "denied"; title: React.ReactNode; description?: React.ReactNode; action?: React.ReactNode }
export const SettingsPermissionNotice = React.forwardRef<HTMLElement, SettingsPermissionNoticeProps>(({ className, state, ...props }, ref) => <DashboardAlert ref={ref} tone={state === "denied" ? "negative" : "neutral"} className={className} {...props}/>)
SettingsPermissionNotice.displayName = "SettingsPermissionNotice"

export interface SettingsSecurityPanelProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> { title: React.ReactNode; description?: React.ReactNode; state?: SettingsSecurityState; actions?: SettingsActionPresentation[] }
export const SettingsSecurityPanel = React.forwardRef<HTMLElement, SettingsSecurityPanelProps>(({ actions = [], children, className, description, state = "available", title, ...props }, ref) => <section ref={ref} data-state={state} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--settings-border)] bg-[var(--settings-panel)] p-4", className)} {...props}><h3 className="text-sm font-semibold">{title}</h3>{description ? <p className="mt-1 text-xs leading-4 text-[var(--settings-muted)]">{description}</p> : null}{children ? <div className="mt-4">{children}</div> : null}{actions.length ? <div className="mt-4 flex flex-wrap gap-2">{actions.map((action) => <Button key={action.id} type="button" variant="outline" className="min-h-11" onClick={action.onSelect} disabled={action.disabled || action.loading} aria-busy={action.loading || undefined}>{action.label}</Button>)}</div> : null}</section>)
SettingsSecurityPanel.displayName = "SettingsSecurityPanel"

export interface SettingsDangerZoneProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> { title: React.ReactNode; description?: React.ReactNode; actions: SettingsActionPresentation[]; severity?: SettingsDangerLevel }
export const SettingsDangerZone = React.forwardRef<HTMLElement, SettingsDangerZoneProps>(({ actions, className, description, severity = "danger", title, ...props }, ref) => <section ref={ref} data-severity={severity} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--settings-danger-border)] bg-[var(--settings-danger-surface)] p-4", className)} {...props}><div className="flex items-start gap-3"><ShieldAlert aria-hidden="true" className="mt-0.5 size-5 shrink-0 text-[var(--settings-state-danger-fg)]"/><div><h2 className="text-base font-semibold text-[var(--settings-state-danger-fg)]">{title}</h2>{description ? <p className="mt-1 text-sm leading-5 text-[var(--dashboard-subtitle)]">{description}</p> : null}</div></div><div className="mt-4 grid gap-3">{actions.map((action) => <div key={action.id} className="flex flex-col gap-3 rounded-[var(--radius-dashboard-input)] border border-[var(--settings-danger-border)] bg-[var(--settings-panel)] p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{action.label}</p>{action.description ? <p className="mt-0.5 text-xs text-[var(--settings-muted)]">{action.description}</p> : null}</div><Button type="button" variant="destructive" className="min-h-11 shrink-0" onClick={action.onSelect} disabled={action.disabled || action.loading} aria-busy={action.loading || undefined}>{action.loading ? "Traitement…" : action.label}</Button></div>)}</div></section>)
SettingsDangerZone.displayName = "SettingsDangerZone"
