"use client"

import * as React from "react"
import { ImageIcon, Loader2, Trash2, UploadCloud } from "lucide-react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import type { SettingsMediaState } from "./settings-foundations"

export interface SettingsMediaFieldProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onSelect"> { label: React.ReactNode; description?: React.ReactNode; value?: React.ReactNode; preview?: React.ReactNode; state?: SettingsMediaState; onSelect?: () => void; onUpload?: (file: File) => void; onRemove?: () => void; disabled?: boolean; loading?: boolean; error?: React.ReactNode; accept?: string; selectLabel?: string; uploadLabel?: string; removeLabel?: string }
export const SettingsMediaField = React.forwardRef<HTMLDivElement, SettingsMediaFieldProps>(({ accept = "image/*", className, description, disabled, error, label, loading, onRemove, onSelect, onUpload, preview, removeLabel = "Retirer", selectLabel = "Choisir", state = "empty", uploadLabel = "Importer", value, ...props }, ref) => { const id = React.useId(); return <div ref={ref} aria-busy={loading || undefined} data-state={state} className={cn("space-y-3 rounded-[var(--radius-dashboard-widget)] border border-[var(--settings-border)] bg-[var(--settings-panel)] p-4", className)} {...props}><div><h3 className="text-sm font-semibold">{label}</h3>{description ? <p className="mt-1 text-xs leading-4 text-[var(--settings-muted)]">{description}</p> : null}</div><div className="flex min-h-32 items-center justify-center overflow-hidden rounded-[var(--radius-dashboard-input)] border border-dashed border-[var(--settings-border)] bg-[var(--settings-section)]">{loading ? <span role="status" className="flex items-center gap-2 text-sm text-[var(--settings-muted)]"><Loader2 aria-hidden="true" className="size-5 animate-spin motion-reduce:animate-none"/>Chargement du média</span> : preview ?? <span className="flex flex-col items-center gap-2 text-sm text-[var(--settings-muted)]"><ImageIcon aria-hidden="true" className="size-6"/>{value ?? "Aucun média sélectionné"}</span>}</div>{error ? <p id={`${id}-error`} role="alert" className="text-xs text-[var(--settings-field-error)]">{error}</p> : null}<div className="flex flex-wrap gap-2">{onSelect ? <Button type="button" variant="outline" className="min-h-11" onClick={onSelect} disabled={disabled || loading}>{selectLabel}</Button> : null}{onUpload ? <><label htmlFor={id} className={cn("dashboard-focus-visible inline-flex min-h-11 cursor-pointer items-center justify-center rounded-[var(--radius-dashboard-button)] border border-[var(--settings-border)] px-4 text-sm font-medium", (disabled || loading) && "pointer-events-none opacity-50")}><UploadCloud aria-hidden="true" className="mr-2 size-4"/>{uploadLabel}</label><input id={id} type="file" accept={accept} disabled={disabled || loading} onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) onUpload(file) }} className="sr-only" aria-describedby={error ? `${id}-error` : undefined}/></> : null}{onRemove ? <Button type="button" variant="outline" className="min-h-11 text-[var(--settings-state-danger-fg)]" onClick={onRemove} disabled={disabled || loading}><Trash2 aria-hidden="true" className="mr-2 size-4"/>{removeLabel}</Button> : null}</div></div> })
SettingsMediaField.displayName = "SettingsMediaField"

export interface SettingsMediaGalleryItem { id: string; preview: React.ReactNode; label: string; description?: React.ReactNode; disabled?: boolean }
export interface SettingsMediaGalleryProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onSelect"> { items: SettingsMediaGalleryItem[]; selectedId?: string; onSelect?: (id: string) => void; onRemove?: (id: string) => void; loading?: boolean; emptyState?: React.ReactNode; ariaLabel?: string }
export const SettingsMediaGallery = React.forwardRef<HTMLDivElement, SettingsMediaGalleryProps>(({ ariaLabel = "Galerie média", className, emptyState, items, loading, onRemove, onSelect, selectedId, ...props }, ref) => <div ref={ref} role="region" aria-label={ariaLabel} aria-busy={loading || undefined} className={cn("min-w-0", className)} {...props}>{loading ? <p role="status" className="p-4 text-sm text-[var(--settings-muted)]">Chargement de la galerie</p> : items.length === 0 ? emptyState ?? <p className="p-4 text-sm text-[var(--settings-muted)]">Aucun média disponible</p> : <ul className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.map((item) => <li key={item.id} className="relative"><button type="button" disabled={item.disabled} aria-pressed={selectedId === item.id} aria-label={item.label} onClick={() => onSelect?.(item.id)} className={cn("dashboard-focus-visible block min-h-11 w-full overflow-hidden rounded-[var(--radius-dashboard-widget)] border-2 bg-[var(--settings-section)]", selectedId === item.id ? "border-[var(--brand-primary)]" : "border-[var(--settings-border)]")}>{item.preview}<span className="block p-2 text-left text-xs font-medium">{item.label}</span></button>{onRemove ? <Button type="button" size="icon" variant="outline" aria-label={`Retirer ${item.label}`} disabled={item.disabled} onClick={() => onRemove(item.id)} className="absolute right-2 top-2 size-11"><Trash2 aria-hidden="true" className="size-4"/></Button> : null}</li>)}</ul>}</div>)
SettingsMediaGallery.displayName = "SettingsMediaGallery"
