import * as React from "react"
import { AlertCircle, CheckCircle2, Clock3, Loader2, LockKeyhole, Pencil, WifiOff } from "lucide-react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import type { SettingsActionPresentation, SettingsSaveState } from "./settings-foundations"

const statusPresentation = { idle: { icon: Clock3, label: "Aucune modification" }, dirty: { icon: Pencil, label: "Modifications non enregistrées" }, saving: { icon: Loader2, label: "Sauvegarde en cours" }, saved: { icon: CheckCircle2, label: "Modifications enregistrées" }, error: { icon: AlertCircle, label: "Échec de la sauvegarde" }, blocked: { icon: LockKeyhole, label: "Sauvegarde bloquée" }, unavailable: { icon: WifiOff, label: "Sauvegarde indisponible" } } as const

export interface SettingsStatusProps extends React.HTMLAttributes<HTMLDivElement> { state: SettingsSaveState | "readOnly"; message?: React.ReactNode }
export const SettingsStatus = React.forwardRef<HTMLDivElement, SettingsStatusProps>(({ className, message, state, ...props }, ref) => { const actual = state === "readOnly" ? { icon: LockKeyhole, label: "Lecture seule" } : statusPresentation[state]; const Icon = actual.icon; return <div ref={ref} role={state === "error" ? "alert" : "status"} aria-live={state === "saving" || state === "saved" ? "polite" : undefined} data-state={state} className={cn("inline-flex min-h-8 items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold", state === "saved" && "bg-[var(--settings-state-saved-bg)] text-[var(--settings-state-saved-fg)]", state === "dirty" && "bg-[var(--settings-state-dirty-bg)] text-[var(--settings-state-dirty-fg)]", state === "saving" && "bg-[var(--settings-state-saving-bg)] text-[var(--settings-state-saving-fg)]", state === "error" && "bg-[var(--settings-state-error-bg)] text-[var(--settings-state-error-fg)]", (state === "blocked" || state === "unavailable" || state === "readOnly" || state === "idle") && "bg-[var(--settings-state-unavailable-bg)] text-[var(--settings-state-unavailable-fg)]", className)} {...props}><Icon aria-hidden="true" className={cn("size-4", state === "saving" && "animate-spin motion-reduce:animate-none")}/><span>{message ?? actual.label}</span></div> })
SettingsStatus.displayName = "SettingsStatus"

function ActionButton({ action, primary = false }: { action: SettingsActionPresentation; primary?: boolean }) { return <Button type="button" variant={primary ? "default" : "outline"} onClick={action.onSelect} disabled={action.disabled || action.loading} aria-busy={action.loading || undefined} className="min-h-11">{action.loading ? <Loader2 aria-hidden="true" className="mr-2 size-4 animate-spin motion-reduce:animate-none"/> : null}{action.label}</Button> }
export interface SettingsSaveBarProps extends React.HTMLAttributes<HTMLDivElement> { state: SettingsSaveState; message?: React.ReactNode; primaryAction?: SettingsActionPresentation; secondaryAction?: SettingsActionPresentation; dirty?: boolean; saving?: boolean }
export const SettingsSaveBar = React.forwardRef<HTMLDivElement, SettingsSaveBarProps>(({ className, dirty, message, primaryAction, saving, secondaryAction, state, ...props }, ref) => { const effectiveState = saving ? "saving" : dirty && state === "idle" ? "dirty" : state; return <div ref={ref} className={cn("sticky bottom-0 z-20 flex flex-col gap-3 border border-[var(--settings-border)] bg-[var(--settings-elevated)] px-4 pt-3 pb-[max(.75rem,var(--safe-bottom,0px))] shadow-[var(--shadow-dashboard-floating)] sm:flex-row sm:items-center sm:justify-between sm:rounded-[var(--radius-dashboard-widget)]", className)} {...props}><SettingsStatus state={effectiveState} message={message}/><div className="flex flex-col-reverse gap-2 sm:flex-row">{secondaryAction ? <ActionButton action={secondaryAction}/> : null}{primaryAction ? <ActionButton action={primaryAction} primary/> : null}</div></div> })
SettingsSaveBar.displayName = "SettingsSaveBar"
