export type OrderCommandErrorCode =
  | "INVALID_COMMAND"
  | "ORDER_NOT_FOUND"
  | "ORDER_ITEM_NOT_FOUND"
  | "RESTAURANT_MISMATCH"
  | "FORBIDDEN_ACTOR"
  | "INVALID_TRANSITION"
  | "ITEM_ALREADY_SERVED"
  | "ITEM_CANCELLED"
  | "INVALID_QUANTITY"
  | "QUANTITY_EXCEEDS_REMAINING"
  | "CONCURRENT_MODIFICATION"
  | "PAYMENT_ALREADY_CONFIRMED"
  | "PAYMENT_AMOUNT_MISMATCH"
  | "PARTIAL_PAYMENT_UNSUPPORTED"
  | "POS_DINE_IN_PAYMENT_REQUIRES_SERVED_ORDER"
  | "PREPAYMENT_REQUIRED_BEFORE_PREPARATION"
  | "ORDER_NOT_READY_FOR_HANDOFF"
  | "ORDER_NOT_READY_FOR_SERVICE"
  | "PAID_ORDER_REQUIRES_REFUND"
  | "FINANCIAL_RECALCULATION_REQUIRED"
  | "IDEMPOTENCY_CONFLICT"
  | "IDEMPOTENCY_CORRUPTED"
  | "STOCK_DEDUCTION_FAILED"

const STATUS: Record<OrderCommandErrorCode, number> = {
  INVALID_COMMAND: 422,
  ORDER_NOT_FOUND: 404,
  ORDER_ITEM_NOT_FOUND: 404,
  RESTAURANT_MISMATCH: 403,
  FORBIDDEN_ACTOR: 403,
  INVALID_TRANSITION: 409,
  ITEM_ALREADY_SERVED: 409,
  ITEM_CANCELLED: 409,
  INVALID_QUANTITY: 422,
  QUANTITY_EXCEEDS_REMAINING: 422,
  CONCURRENT_MODIFICATION: 409,
  PAYMENT_ALREADY_CONFIRMED: 409,
  PAYMENT_AMOUNT_MISMATCH: 422,
  PARTIAL_PAYMENT_UNSUPPORTED: 422,
  POS_DINE_IN_PAYMENT_REQUIRES_SERVED_ORDER: 409,
  PREPAYMENT_REQUIRED_BEFORE_PREPARATION: 409,
  ORDER_NOT_READY_FOR_HANDOFF: 409,
  ORDER_NOT_READY_FOR_SERVICE: 409,
  PAID_ORDER_REQUIRES_REFUND: 409,
  FINANCIAL_RECALCULATION_REQUIRED: 409,
  IDEMPOTENCY_CONFLICT: 409,
  IDEMPOTENCY_CORRUPTED: 500,
  STOCK_DEDUCTION_FAILED: 503,
}

export class OrderCommandError extends Error {
  readonly code: OrderCommandErrorCode
  readonly status: number
  readonly retryable: boolean

  constructor(
    code: OrderCommandErrorCode,
    message: string,
    retryable = false
  ) {
    super(message)
    this.name = "OrderCommandError"
    this.code = code
    this.status = STATUS[code]
    this.retryable = retryable
  }
}
