export const LEGACY_STOCK_WRITE_PATHS = [
  {
    id: "inventory-item-create",
    trigger: "manager_inventory_create",
    authority: "InventoryService.createInventoryItem",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "creates_item_and_initial_quantity",
    risk: "P1",
  },
  {
    id: "inventory-stock-add",
    trigger: "manager_inventory_add",
    authority: "InventoryService.addInventoryStock",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "increments_quantity_without_movement",
    risk: "P1",
  },
  {
    id: "inventory-stock-replace",
    trigger: "manager_inventory_adjust",
    authority: "InventoryService.adjustInventoryStock",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "replaces_quantity_without_movement",
    risk: "P0",
  },
  {
    id: "inventory-cost-update",
    trigger: "manager_inventory_cost",
    authority: "InventoryService.updateInventoryCost",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "replaces_unit_cost",
    risk: "P2",
  },
  {
    id: "inventory-threshold-update",
    trigger: "service_only",
    authority: "InventoryService.updateInventoryMinThreshold",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "replaces_low_stock_threshold",
    risk: "P3",
  },
  {
    id: "inventory-tracking-mode-update",
    trigger: "manager_inventory_tracking_mode",
    authority: "InventoryService.updateTrackingMode",
    collections: ["inventoryItems"],
    effect: "changes_automatic_consumption_eligibility",
    risk: "P1",
  },
  {
    id: "inventory-physical-verification",
    trigger: "manager_inventory_verify",
    authority: "InventoryService.verifyInventoryStock",
    collections: ["inventoryItems", "inventoryMovements"],
    effect: "replaces_quantity_and_attempts_manual_movement",
    risk: "P0",
  },
  {
    id: "inventory-reconciliation",
    trigger: "service_only",
    authority: "InventoryService.reconcileStock",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "replaces_quantity_and_count_snapshot_without_movement",
    risk: "P1",
  },
  {
    id: "inventory-consumption-statistics",
    trigger: "payment_consumption_only",
    authority: "InventoryService.updateConsumptionStats",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "updates_consumption_averages",
    risk: "P2",
  },
  {
    id: "kitchen-order-consumption",
    trigger: "OrderService.updateOrderStatus:preparing",
    authority: "InventoryService.handleOrderSentToKitchen",
    collections: ["orders", "products", "inventoryItems", "inventoryMovements"],
    effect: "decrements_recipe_and_marks_order_processed",
    risk: "P0",
  },
  {
    id: "legacy-payment-product-stock",
    trigger: "OrderService.processPayment",
    authority: "OrderService.decrementStockForOrderItems",
    collections: ["orders", "orderItems", "inventory"],
    effect: "decrements_legacy_product_linked_quantity_with_zero_floor",
    risk: "P0",
  },
  {
    id: "payment-order-consumption",
    trigger: "no_active_caller_identified",
    authority: "InventoryService.handleOrderPaid",
    collections: [
      "products",
      "inventoryItems",
      "inventoryMovements",
      "inventoryLogs",
      "orders/costSnapshot",
      "inventoryAlerts",
    ],
    effect: "decrements_recipe_and_records_cost_by_payment",
    risk: "P0",
  },
  {
    id: "supply-expense-reception",
    trigger: "manager_expense_supply",
    authority: "SupplyExpenseService.createExpense",
    collections: [
      "expenses",
      "expenseLogs",
      "inventoryItems",
      "inventoryMovements",
      "suppliers",
      "treasuryAccounts",
      "cashMovements",
    ],
    effect: "increments_quantity_and_recalculates_weighted_cost",
    risk: "P0",
  },
  {
    id: "inventory-seed-service",
    trigger: "InventoryService.seedInventoryItems",
    authority: "InventoryService.createInventoryItem",
    collections: ["inventoryItems", "inventoryAlerts"],
    effect: "creates_three_default_items",
    risk: "P3",
  },
  {
    id: "inventory-seed-script",
    trigger: "manual_admin_script",
    authority: "scripts/seed-inventory-items.js",
    collections: ["inventoryItems"],
    effect: "merge_writes_three_default_items",
    risk: "P1",
  },
] as const

export const LEGACY_STOCK_READ_PATHS = [
  {
    id: "manager-inventory",
    consumer: "ManagerInventoryPage",
    collections: ["inventoryItems", "inventoryLogs", "inventoryAlerts"],
    representation: "operational_stock_cost_margin_alerts",
  },
  {
    id: "legacy-manager-dashboard",
    consumer: "DashboardClient via AnalyticsService",
    collections: ["inventory"],
    representation: "legacy_low_stock_count",
  },
  {
    id: "manager-expenses",
    consumer: "ManagerExpensesPage",
    collections: ["inventoryItems", "suppliers", "expenses", "treasuryAccounts"],
    representation: "supply_entry_and_expense_history",
  },
  {
    id: "manager-product-editor",
    consumer: "ManagerClient",
    collections: ["inventoryItems", "inventoryAlerts", "products"],
    representation: "recipe_configuration_cost_and_dashboard_alerts",
  },
  {
    id: "owner-dashboard",
    consumer: "OwnerPage",
    collections: ["inventoryItems", "inventoryAlerts", "inventoryLogs"],
    representation: "stock_value_consumed_cost_losses_and_critical_items",
  },
  {
    id: "manager-suppliers",
    consumer: "ManagerSuppliersPage",
    collections: ["suppliers"],
    representation: "supplier_balances",
  },
  {
    id: "order-consumption",
    consumer: "InventoryService",
    collections: ["orders", "products", "inventoryItems", "inventoryLogs"],
    representation: "recipe_consumption_and_cost",
  },
] as const

export type LegacyStockWritePath = (typeof LEGACY_STOCK_WRITE_PATHS)[number]
export type LegacyStockReadPath = (typeof LEGACY_STOCK_READ_PATHS)[number]
