"use client"

import * as React from "react"
import { Check, Clipboard } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { cn } from "@/lib/utils"

export interface OrderDetailSheetProps { open: boolean; onOpenChange: (open: boolean) => void; title: React.ReactNode; description: React.ReactNode; status?: React.ReactNode; summary?: React.ReactNode; children?: React.ReactNode; footer?: React.ReactNode; initialFocusRef?: React.RefObject<HTMLElement | null>; className?: string }
export function OrderDetailSheet({ children, className, description, footer, initialFocusRef, onOpenChange, open, status, summary, title }: OrderDetailSheetProps) { return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" onOpenAutoFocus={(event) => { if (initialFocusRef?.current) { event.preventDefault(); initialFocusRef.current.focus() } }} className={cn("dashboard-reduced-motion flex h-[100dvh] w-full max-w-none flex-col gap-0 overflow-hidden border-[var(--order-border)] bg-[var(--order-surface)] p-0 [&>button]:flex [&>button]:min-h-10 [&>button]:min-w-10 [&>button]:items-center [&>button]:justify-center sm:w-[min(92vw,42rem)] sm:max-w-[42rem]", className)}><SheetHeader className="border-b border-[var(--order-divider)] px-4 py-5 pr-14 text-left sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><SheetTitle className="break-words text-xl text-[var(--dashboard-title)]">{title}</SheetTitle><SheetDescription className="mt-1 break-words text-[var(--dashboard-muted)]">{description}</SheetDescription></div>{status}</div>{summary ? <div className="mt-4">{summary}</div> : null}</SheetHeader><div className="min-h-0 flex-1 overflow-x-hidden overflow-y-auto overscroll-contain px-4 py-5 sm:px-6">{children}</div>{footer ? <SheetFooter className="sticky bottom-0 border-t border-[var(--order-divider)] bg-[var(--order-surface)] px-4 pb-[max(1rem,var(--safe-bottom))] pt-3 sm:px-6">{footer}</SheetFooter> : null}</SheetContent></Sheet> }

export interface OrderInfoItem { label: React.ReactNode; value?: React.ReactNode; icon?: React.ReactNode; copyable?: boolean; onCopy?: () => void; copyLabel?: string }
export interface OrderInfoGridProps extends React.HTMLAttributes<HTMLDListElement> { items: OrderInfoItem[]; emptyValue?: React.ReactNode }
export const OrderInfoGrid = React.forwardRef<HTMLDListElement, OrderInfoGridProps>(({ className, emptyValue = "Non renseigné", items, ...props }, ref) => <dl ref={ref} className={cn("grid gap-3 sm:grid-cols-2", className)} {...props}>{items.map((item, index) => <div key={index} className="min-w-0 rounded-[var(--radius-dashboard-button)] border border-[var(--order-border)] bg-[var(--order-surface-muted)] p-3"><dt className="flex items-center gap-2 text-xs font-semibold text-[var(--dashboard-label)]">{item.icon ? <span aria-hidden="true" className="[&_svg]:size-4">{item.icon}</span> : null}{item.label}</dt><dd className="mt-1 flex min-w-0 items-center justify-between gap-2 text-sm font-semibold text-[var(--dashboard-title)]"><span className="min-w-0 break-words">{item.value ?? emptyValue}</span>{item.copyable && item.onCopy && item.value != null ? <Button type="button" variant="ghost" size="icon" className="min-h-10 min-w-10 shrink-0" onClick={item.onCopy} aria-label={item.copyLabel ?? `Copier ${String(item.label)}`}><Clipboard aria-hidden="true" className="size-4" /></Button> : null}</dd></div>)}</dl>)
OrderInfoGrid.displayName = "OrderInfoGrid"

export interface OrderItemPresentation { id: string; name: React.ReactNode; quantity: React.ReactNode; options?: React.ReactNode; note?: React.ReactNode; destination?: React.ReactNode; unitPrice?: React.ReactNode; total?: React.ReactNode; bundle?: React.ReactNode; group?: React.ReactNode }
export interface OrderItemsListProps extends React.HTMLAttributes<HTMLUListElement> { items: OrderItemPresentation[]; empty?: React.ReactNode }
export const OrderItemsList = React.forwardRef<HTMLUListElement, OrderItemsListProps>(({ className, empty = "Aucun article", items, ...props }, ref) => { if (!items.length) return <p className={cn("rounded-[var(--radius-dashboard-button)] border border-dashed border-[var(--order-border)] p-4 text-sm text-[var(--dashboard-muted)]", className)}>{empty}</p>; return <ul ref={ref} className={cn("divide-y divide-[var(--order-divider)] rounded-[var(--radius-dashboard-card)] border border-[var(--order-border)]", className)} {...props}>{items.map((item) => <li key={item.id} className="p-3 sm:p-4">{item.group ? <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-[var(--dashboard-label)]">{item.group}</p> : null}<div className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="break-words font-semibold text-[var(--dashboard-title)]">{item.quantity} × {item.name}</p>{item.bundle ? <div className="mt-1 break-words text-sm text-[var(--dashboard-subtitle)]">{item.bundle}</div> : null}{item.options ? <div className="mt-1 break-words text-sm text-[var(--dashboard-muted)]">{item.options}</div> : null}{item.note ? <p className="mt-2 break-words rounded bg-[var(--order-surface-muted)] p-2 text-sm text-[var(--dashboard-subtitle)]">{item.note}</p> : null}{item.destination ? <p className="mt-1 break-words text-xs font-semibold text-[var(--dashboard-label)]">{item.destination}</p> : null}</div>{item.unitPrice != null || item.total != null ? <div className="min-w-0 text-left tabular-nums sm:shrink-0 sm:text-right">{item.total != null ? <p className="break-words font-semibold text-[var(--dashboard-value)]">{item.total}</p> : null}{item.unitPrice != null ? <p className="break-words text-xs text-[var(--dashboard-muted)]">{item.unitPrice}</p> : null}</div> : null}</div></li>)}</ul> })
OrderItemsList.displayName = "OrderItemsList"

export type OrderTimelineState = "completed" | "current" | "future" | "cancelled" | "error"
export interface OrderTimelineItem { id: string; label: React.ReactNode; timestamp?: React.ReactNode; description?: React.ReactNode; state: OrderTimelineState; actor?: React.ReactNode }
export interface OrderTimelineProps extends React.HTMLAttributes<HTMLOListElement> { items: OrderTimelineItem[]; currentId?: string; orientation?: "vertical" | "horizontal"; ariaLabel?: string }
const timelineStateClasses: Record<OrderTimelineState, string> = { completed: "border-[var(--data-positive)] bg-[var(--data-positive)] text-white", current: "border-[var(--data-info)] bg-[var(--order-surface)] text-[var(--data-info)]", future: "border-[var(--order-border)] bg-[var(--order-surface-muted)] text-[var(--dashboard-muted)]", cancelled: "border-[var(--data-negative)] bg-[var(--order-surface)] text-[var(--data-negative)]", error: "border-[var(--data-negative)] bg-[var(--data-negative)] text-white" }
export const OrderTimeline = React.forwardRef<HTMLOListElement, OrderTimelineProps>(({ ariaLabel = "Progression de la commande", className, currentId, items, orientation = "vertical", ...props }, ref) => <ol ref={ref} aria-label={ariaLabel} className={cn(orientation === "vertical" ? "space-y-0" : "grid auto-cols-fr grid-flow-col gap-2 overflow-x-auto", className)} {...props}>{items.map((item, index) => { const current = item.id === currentId || item.state === "current"; return <li key={item.id} aria-current={current ? "step" : undefined} className={cn("relative min-w-0", orientation === "vertical" && "grid grid-cols-[1.75rem_minmax(0,1fr)] gap-3 pb-5 last:pb-0")}><span aria-hidden="true" className={cn("relative z-10 flex size-7 items-center justify-center rounded-full border-2", timelineStateClasses[item.state])}>{item.state === "completed" ? <Check className="size-4" /> : <span className="size-1.5 rounded-full bg-current" />}</span>{orientation === "vertical" && index < items.length - 1 ? <span aria-hidden="true" className="absolute left-[0.8125rem] top-7 h-[calc(100%-1.75rem)] w-px bg-[var(--order-divider)]" /> : null}<div className={cn("min-w-0", orientation === "horizontal" && "mt-2")}><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="font-semibold text-[var(--dashboard-title)]">{item.label}<span className="sr-only"> — {item.state === "completed" ? "terminé" : item.state === "current" ? "étape actuelle" : item.state === "future" ? "à venir" : item.state === "cancelled" ? "annulé" : "en erreur"}</span></p>{item.timestamp ? <time className="text-xs tabular-nums text-[var(--dashboard-muted)]">{item.timestamp}</time> : null}</div>{item.description ? <p className="mt-1 text-sm text-[var(--dashboard-muted)]">{item.description}</p> : null}{item.actor ? <p className="mt-1 text-xs text-[var(--dashboard-label)]">Par {item.actor}</p> : null}</div></li> })}</ol>)
OrderTimeline.displayName = "OrderTimeline"
