import * as React from "react"
import Link from "next/link"
import { Loader2 } from "lucide-react"
import { cn } from "@/lib/utils"
import type { OrderAgePresentation, OrderChannelPresentation, OrderDensity, OrderPaymentPresentation, OrderPriorityDisplay, OrderStatusPresentation } from "./order-foundations"
import { OrderAgeIndicator, OrderChannelBadge, OrderPaymentBadge, OrderStatusBadge } from "./order-status"

export interface OrderItemSummaryPresentation { name: React.ReactNode; quantity: React.ReactNode; optionsSummary?: React.ReactNode; destination?: React.ReactNode }
export interface OrderItemsSummaryProps extends React.HTMLAttributes<HTMLUListElement> { items: OrderItemSummaryPresentation[]; maxVisible?: number; remainingLabel?: (count: number) => React.ReactNode }
export const OrderItemsSummary = React.forwardRef<HTMLUListElement, OrderItemsSummaryProps>(({ className, items, maxVisible = 3, remainingLabel = (count) => `+${count} autre${count > 1 ? "s" : ""}`, ...props }, ref) => { const visible = items.slice(0, Math.max(0, maxVisible)); const remaining = Math.max(0, items.length - visible.length); if (!items.length) return null; return <ul ref={ref} className={cn("space-y-1.5", className)} {...props}>{visible.map((item, index) => <li key={index} className="flex min-w-0 items-start justify-between gap-3 text-sm"><span className="min-w-0"><span className="font-semibold text-[var(--dashboard-title)]">{item.quantity} × {item.name}</span>{item.optionsSummary ? <span className="block text-xs text-[var(--dashboard-muted)]">{item.optionsSummary}</span> : null}</span>{item.destination ? <span className="shrink-0 text-xs text-[var(--dashboard-muted)]">{item.destination}</span> : null}</li>)}{remaining ? <li className="text-xs font-semibold text-[var(--dashboard-muted)]">{remainingLabel(remaining)}</li> : null}</ul> })
OrderItemsSummary.displayName = "OrderItemsSummary"

export interface OrderCardProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> {
  reference: string; title?: React.ReactNode; subtitle?: React.ReactNode; status: OrderStatusPresentation; payment?: OrderPaymentPresentation; channel?: OrderChannelPresentation; age?: OrderAgePresentation; total?: React.ReactNode; itemCount?: React.ReactNode; customer?: React.ReactNode; table?: React.ReactNode; destination?: React.ReactNode; priority?: OrderPriorityDisplay; actions?: React.ReactNode; onOpen?: () => void; href?: string; selected?: boolean; disabled?: boolean; loading?: boolean; density?: OrderDensity; summary?: React.ReactNode; children?: React.ReactNode; footer?: React.ReactNode
}
export const OrderCard = React.forwardRef<HTMLElement, OrderCardProps>(({ actions, age, channel, children, className, customer, density = "comfortable", destination, disabled = false, footer, href, itemCount, loading = false, onOpen, payment, priority = "normal", reference, selected = false, status, subtitle, summary, table, title, total, ...props }, ref) => {
  const accessibleName = `Ouvrir la commande ${reference}, ${status.label}`
  const openClasses = "dashboard-focus-visible inline-flex min-h-[var(--target-dashboard-min)] items-center rounded-[var(--radius-dashboard-button)] text-sm font-semibold text-[var(--data-info)] hover:underline disabled:pointer-events-none disabled:opacity-50"
  return <article ref={ref} aria-busy={loading || undefined} data-density={density} data-priority={priority} className={cn("dashboard-reduced-motion rounded-[var(--radius-dashboard-card)] border bg-[var(--order-surface)] shadow-[var(--shadow-dashboard-surface)] transition-[border-color,background-color,box-shadow] [transition-duration:var(--motion-dashboard-hover)]", density === "comfortable" ? "p-4" : "p-3", selected ? "border-[var(--order-border-active)] ring-2 ring-[var(--order-border-active)]/20" : "border-[var(--order-border)]", priority === "warning" && "border-[var(--order-priority-warning)]", priority === "overdue" && "border-[var(--order-priority-overdue)]", priority === "critical" && "border-2 border-[var(--order-priority-critical)]", disabled && "opacity-60", className)} {...props}>
    <div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--dashboard-label)]">{reference}</p>{title ? <h3 className="mt-1 text-base font-bold leading-5 text-[var(--dashboard-title)]">{title}</h3> : null}{subtitle ? <p className="mt-0.5 text-sm text-[var(--dashboard-muted)]">{subtitle}</p> : null}</div>{loading ? <Loader2 aria-hidden="true" className="size-5 shrink-0 animate-spin text-[var(--dashboard-muted)] motion-reduce:animate-none" /> : null}</div>
    <div className="mt-3 flex flex-wrap items-center gap-2"><OrderStatusBadge {...status} size={density === "compact" ? "compact" : "standard"} />{age ? <OrderAgeIndicator {...age} /> : null}{channel ? <OrderChannelBadge {...channel} size="compact" /> : null}</div>
    {customer || table || destination ? <dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{customer ? <div><dt className="sr-only">Client</dt><dd className="text-[var(--dashboard-subtitle)]">{customer}</dd></div> : null}{table ? <div><dt className="sr-only">Table</dt><dd className="text-[var(--dashboard-subtitle)]">{table}</dd></div> : null}{destination ? <div className="sm:col-span-2"><dt className="sr-only">Destination</dt><dd className="text-[var(--dashboard-subtitle)]">{destination}</dd></div> : null}</dl> : null}
    {summary ? <div className="mt-3 rounded-[var(--radius-dashboard-button)] bg-[var(--order-surface-muted)] p-3">{summary}</div> : null}{children}
    {payment || total != null || itemCount != null ? <div className="mt-3 flex flex-wrap items-end justify-between gap-3 border-t border-[var(--order-divider)] pt-3">{payment ? <OrderPaymentBadge {...payment} size="compact" /> : <span /> }<div className="text-right">{itemCount != null ? <p className="text-xs text-[var(--dashboard-muted)]">{itemCount}</p> : null}{total != null ? <p className="break-words text-lg font-bold tabular-nums text-[var(--dashboard-value)]">{total}</p> : null}</div></div> : null}
    <div className="mt-3 flex flex-wrap items-center justify-between gap-2">{href ? <Link href={href} aria-label={accessibleName} className={openClasses} aria-disabled={disabled || undefined} tabIndex={disabled ? -1 : undefined}>Voir le détail</Link> : onOpen ? <button type="button" onClick={onOpen} disabled={disabled || loading} aria-label={accessibleName} className={openClasses}>Voir le détail</button> : <span />}{actions ? <div className="min-w-0">{actions}</div> : null}</div>{footer ? <div className="mt-3 border-t border-[var(--order-divider)] pt-3">{footer}</div> : null}
  </article>
})
OrderCard.displayName = "OrderCard"

export interface OrderCardSkeletonProps extends React.HTMLAttributes<HTMLDivElement> { density?: OrderDensity }
export function OrderCardSkeleton({ density = "comfortable", className, ...props }: OrderCardSkeletonProps) { return <div role="status" aria-label="Chargement d’une commande" className={cn("dashboard-reduced-motion rounded-[var(--radius-dashboard-card)] border border-[var(--order-border)] bg-[var(--order-surface)]", density === "comfortable" ? "p-4" : "p-3", className)} {...props}><div className="h-3 w-24 animate-pulse rounded bg-[var(--order-surface-muted)] motion-reduce:animate-none" /><div className="mt-3 flex gap-2"><div className="h-7 w-28 animate-pulse rounded-full bg-[var(--order-surface-muted)] motion-reduce:animate-none" /><div className="h-7 w-20 animate-pulse rounded-full bg-[var(--order-surface-muted)] motion-reduce:animate-none" /></div><div className="mt-4 space-y-2"><div className="h-4 w-full animate-pulse rounded bg-[var(--order-surface-muted)] motion-reduce:animate-none" /><div className="h-4 w-3/4 animate-pulse rounded bg-[var(--order-surface-muted)] motion-reduce:animate-none" /></div><div className="mt-4 flex justify-between border-t border-[var(--order-divider)] pt-3"><div className="h-7 w-24 animate-pulse rounded bg-[var(--order-surface-muted)] motion-reduce:animate-none" /><div className="h-10 w-28 animate-pulse rounded bg-[var(--order-surface-muted)] motion-reduce:animate-none" /></div></div> }
