"use client"

import * as React from "react"
import { Banknote, ReceiptText, Wallet } from "lucide-react"
import { DataQualityBadge, FreshnessIndicator, ReportMetricCard, ReportsEmptyState, ReportsErrorState, ReportsEstimatedState, ReportsHeader, ReportsPage, ReportsPaymentSummary, ReportsSummary, ReportsTable, ReportsTableToolbar } from "@/components/reports-ui"
import { ManagerPeriodFilter } from "@/components/layout/manager-period-filter"
import { MANAGER_MOVEMENT_COLUMNS, type ManagerReportsViewModel } from "./manager-reports-view-model"

interface Props {
  model: ManagerReportsViewModel; errors?: string[]
  directionFilter: string; accountFilter: string; sourceFilter: string; accountOptions: Array<{ id: string; label: string }>; sourceOptions: Array<{ id: string; label: string }>
  onDirectionFilterChange: (value: string) => void; onAccountFilterChange: (value: string) => void; onSourceFilterChange: (value: string) => void
}
export function ManagerReportsView({ accountFilter, accountOptions, directionFilter, errors = [], model, onAccountFilterChange, onDirectionFilterChange, onSourceFilterChange, sourceFilter, sourceOptions }: Props) {
  const estimated = model.balanceQuality === "estimated" || model.movementQuality === "estimated"
  const movementsUnavailable = errors.includes("mouvements")
  return <ReportsPage className="pb-20 md:pb-6"><ReportsHeader title="Rapports financiers" subtitle="Suivez les soldes, entrées, dépenses et mouvements disponibles pour l’exploitation." meta={<>Période active : <strong>{model.periodLabel}</strong> · Certains soldes restent globaux lorsque le fallback historique est utilisé.</>} context={<><DataQualityBadge quality={errors.length ? "unavailable" : estimated ? "estimated" : "complete"} /><FreshnessIndicator freshness={errors.length ? "unknown" : "live"} label={errors.length ? "Fraîcheur partiellement indisponible" : undefined} /></>} actions={<ManagerPeriodFilter />} />
    {errors.length ? <ReportsErrorState title="Certaines données Manager sont indisponibles" description={`Domaines concernés : ${errors.join(", ")}. Les données restantes demeurent visibles.`} /> : null}
    {estimated ? <ReportsEstimatedState title="Source historique utilisée" description="La vue conserve ses fallbacks existants lorsque les comptes ou mouvements ne portent pas une valeur exploitable. Aucune source n’a été fusionnée." /> : null}
    <section aria-labelledby="manager-report-kpis" className="space-y-3"><h2 id="manager-report-kpis" className="text-[length:var(--text-dashboard-section-title)] font-semibold">Indicateurs opérationnels</h2><ReportsSummary className="xl:grid-cols-3"><ReportMetricCard label="Solde total" value={model.balance.replace(" FCFA", "")} unit="FCFA" description="Comptes courants ou fallback financier historique." icon={<Wallet />} quality={model.balanceQuality} freshness="live" /><ReportMetricCard label="Entrées totales" value={movementsUnavailable ? "—" : model.deposits.replace(" FCFA", "")} unit={movementsUnavailable ? undefined : "FCFA"} description={model.periodLabel} icon={<ReceiptText />} quality={movementsUnavailable ? "unavailable" : model.movementQuality} freshness="live" /><ReportMetricCard label="Dépenses totales" value={movementsUnavailable ? "—" : model.expenses.replace(" FCFA", "")} unit={movementsUnavailable ? undefined : "FCFA"} description={model.periodLabel} icon={<Banknote />} quality={movementsUnavailable ? "unavailable" : model.movementQuality} freshness="live" /></ReportsSummary></section>
    <ReportsPaymentSummary title="Répartition par compte" description="Soldes de trésorerie par support ; ils ne constituent pas une ventilation du chiffre d’affaires.">{model.accounts.map((account) => <article key={account.id} className="rounded-[var(--radius-dashboard-card)] bg-[var(--reports-muted)] p-4"><p className="text-xs font-semibold uppercase text-[var(--dashboard-label)]">{account.name}</p><p className="mt-2 break-words text-xl font-bold tabular-nums">{account.value}</p><p className="mt-1 text-xs text-[var(--dashboard-muted)]">{account.kind}</p></article>)}</ReportsPaymentSummary>
    <section aria-labelledby="manager-report-history" className="space-y-3"><div><h2 id="manager-report-history" className="text-[length:var(--text-dashboard-section-title)] font-semibold">Historique des mouvements</h2><p className="text-sm text-[var(--dashboard-muted)]">Source : cashMovements enrichi, compatible avec les anciens mouvements.</p></div><ReportsTableToolbar count={`${model.movements.length} mouvement${model.movements.length > 1 ? "s" : ""}`} filters={<div className="grid w-full gap-2 sm:grid-cols-3"><Select label="Type" value={directionFilter} onChange={onDirectionFilterChange} options={[{ id: "all", label: "Tous" }, { id: "in", label: "Entrées" }, { id: "out", label: "Sorties" }, { id: "transfer", label: "Transferts" }]} /><Select label="Compte" value={accountFilter} onChange={onAccountFilterChange} options={[{ id: "all", label: "Tous" }, ...accountOptions]} /><Select label="Source" value={sourceFilter} onChange={onSourceFilterChange} options={[{ id: "all", label: "Toutes" }, ...sourceOptions]} /></div>} /><ReportsTable label="Historique des mouvements" caption={`Mouvements Manager · ${model.periodLabel}`} columns={MANAGER_MOVEMENT_COLUMNS} rows={model.movements} getRowKey={(row) => row.id} errorState={movementsUnavailable ? <ReportsErrorState title="Historique des mouvements indisponible" description={`Les mouvements de ${model.periodLabel} n’ont pas pu être chargés.`} /> : undefined} emptyState={<ReportsEmptyState title={directionFilter !== "all" || accountFilter !== "all" || sourceFilter !== "all" ? "Aucun mouvement ne correspond aux filtres" : "Aucune donnée pour cette période"} description={directionFilter !== "all" || accountFilter !== "all" || sourceFilter !== "all" ? "Modifiez les filtres existants pour retrouver d’autres mouvements." : undefined} />} /></section>
  </ReportsPage>
}
function Select({ label, onChange, options, value }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ id: string; label: string }> }) { const id = React.useId(); return <label htmlFor={id} className="text-xs font-semibold text-[var(--dashboard-label)]">{label}<select id={id} value={value} onChange={(event) => onChange(event.target.value)} className="dashboard-focus-visible mt-1 min-h-[var(--target-dashboard-recommended)] w-full rounded-[var(--radius-dashboard-input)] border border-[var(--reports-border)] bg-[var(--reports-panel)] px-3 text-sm">{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label> }
