import assert from "node:assert/strict"
import test,{after,before} from "node:test"
import {deleteApp,initializeApp} from "firebase-admin/app"
import {getFirestore} from "firebase-admin/firestore"
import {executePreparationIssueCommand} from "../../src/server/preparation/preparation-issue-service.ts"
const enabled=Boolean(process.env.FIRESTORE_EMULATOR_HOST);let app,db
before(()=>{if(enabled){app=initializeApp({projectId:"preparation-issues"},`issues-${Date.now()}`);db=getFirestore(app)}});after(async()=>{if(app)await deleteApp(app)})
async function seed(){const id=`r-${Date.now()}`,root=db.collection("restaurants").doc(id);await root.set({name:"R"});await Promise.all([root.collection("staff").doc("hot-user").set({role:"kitchen",allowedPreparationStationIds:["hot"]}),root.collection("staff").doc("cold-user").set({role:"kitchen",allowedPreparationStationIds:["cold"]}),root.collection("orders").doc("order-1").collection("orderItems").doc("item-1").set({restaurantId:id,orderId:"order-1",productId:"p",nameSnapshot:"Plat",preparationMode:"kitchen",preparationStationId:"hot",preparationStationName:"Cuisine chaude",preparationStationCode:"HOT",status:"pending"})]);return{id,root}}
test("signalement, visibilité documentaire et résolution sans annuler la ligne",{skip:!enabled},async()=>{const {id,root}=await seed();await executePreparationIssueCommand({db,restaurantId:id,actor:{uid:"hot-user",role:"kitchen"},command:{type:"REPORT",orderId:"order-1",orderItemId:"item-1",reason:"MISSING_INGREDIENT",comment:"Tomates"}});const issue=(await root.collection("preparationIssues").doc("order-1--item-1").get()).data();assert.equal(issue.status,"OPEN");assert.equal(issue.preparationStationId,"hot");assert.equal((await root.collection("orders").doc("order-1").collection("orderItems").doc("item-1").get()).data().status,"pending");await executePreparationIssueCommand({db,restaurantId:id,actor:{uid:"hot-user",role:"kitchen"},command:{type:"RESOLVE",orderId:"order-1",orderItemId:"item-1"}});assert.equal((await root.collection("preparationIssues").doc("order-1--item-1").get()).data().status,"RESOLVED")})
test("un autre poste ne peut ni signaler ni résoudre",{skip:!enabled},async()=>{const {id}=await seed();await assert.rejects(executePreparationIssueCommand({db,restaurantId:id,actor:{uid:"cold-user",role:"kitchen"},command:{type:"REPORT",orderId:"order-1",orderItemId:"item-1",reason:"ORDER_ERROR",comment:""}}),e=>e.code==="FORBIDDEN")})
