import * as React from "react"
import { ImageIcon, Plus } from "lucide-react"
import { cn } from "@/lib/utils"
import type { PosProductAvailability } from "./pos-foundations"

const availabilityClasses: Record<PosProductAvailability, string> = { available: "text-[var(--data-positive)]", limited: "text-[var(--data-warning)]", unavailable: "text-[var(--data-negative)]", unknown: "text-[var(--dashboard-muted)]" }
export interface PosProductCardProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "name" | "onSelect"> { name: React.ReactNode; description?: React.ReactNode; imageUrl?: string | null; imageAlt?: string; price: React.ReactNode; availability?: PosProductAvailability; availabilityLabel?: React.ReactNode; destination?: React.ReactNode; configurable?: boolean; actionLabel?: string; onSelect?: () => void; loading?: boolean; selected?: boolean }
export const PosProductCard = React.forwardRef<HTMLButtonElement, PosProductCardProps>(({ actionLabel = "Sélectionner le produit", availability = "unknown", availabilityLabel, className, configurable, description, destination, disabled, imageAlt = "", imageUrl, loading, name, onSelect, price, selected, ...props }, ref) => <button ref={ref} type="button" onClick={onSelect} disabled={disabled || loading} aria-pressed={selected || undefined} aria-busy={loading || undefined} className={cn("dashboard-focus-visible group flex min-h-[11rem] min-w-0 flex-col rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-panel)] p-3 text-left shadow-[var(--shadow-dashboard-surface)] transition-[border-color,background-color] duration-150 disabled:cursor-not-allowed disabled:opacity-55", selected && "border-[var(--brand-primary)]", className)} {...props}><div className="relative mb-3 aspect-[4/3] w-full overflow-hidden rounded-[var(--radius-dashboard-input)] bg-[var(--pos-muted)]">{imageUrl ? <img src={imageUrl} alt={imageAlt} loading="lazy" className="size-full object-cover"/> : <span className="flex size-full items-center justify-center text-[var(--dashboard-muted)]"><ImageIcon aria-hidden="true" className="size-7"/></span>}</div><span className="min-w-0 text-sm font-semibold leading-5">{name}</span>{description ? <span className="mt-1 line-clamp-2 text-xs leading-4 text-[var(--dashboard-muted)]">{description}</span> : null}<span className="mt-auto pt-2 text-base font-bold tabular-nums text-[var(--dashboard-value)]">{price}</span>{availabilityLabel ? <span className={cn("mt-1 text-xs font-medium", availabilityClasses[availability])}>{availabilityLabel}</span> : null}{destination || configurable ? <span className="mt-1 text-xs text-[var(--dashboard-muted)]">{destination}{destination && configurable ? " · " : null}{configurable ? "Options" : null}</span> : null}<span className="mt-3 inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-dashboard-button)] bg-[var(--brand-primary)] px-3 text-sm font-semibold text-[var(--action-primary-fg)]"><Plus aria-hidden="true" className="size-4"/>{actionLabel}</span></button>)
PosProductCard.displayName = "PosProductCard"
