"use client"
import * as React from "react"
import { Search, X } from "lucide-react"
import { cn } from "@/lib/utils"
import { Input } from "@/components/ui/input"
import type { PosCategoryPresentation } from "./pos-foundations"

export interface PosCatalogProps extends React.HTMLAttributes<HTMLElement> { header?: React.ReactNode; categories?: React.ReactNode; footer?: React.ReactNode; contentClassName?: string; loading?: boolean; loadingState?: React.ReactNode; emptyState?: React.ReactNode; errorState?: React.ReactNode }
export const PosCatalog = React.forwardRef<HTMLElement, PosCatalogProps>(({ categories, children, className, contentClassName, emptyState, errorState, footer, header, loading, loadingState, ...props }, ref) => <section ref={ref} className={cn("flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-catalog)]", className)} {...props}>{header ? <div className="shrink-0 border-b border-[var(--pos-divider)] p-3">{header}</div> : null}{categories ? <div className="shrink-0 overflow-y-hidden bg-[var(--pos-catalog)] p-3 pb-0">{categories}</div> : null}<div className={cn("min-h-0 flex-1 overflow-y-auto overscroll-contain p-3", contentClassName)}>{errorState ?? (loading ? loadingState : children ?? emptyState)}</div>{footer ? <div className="shrink-0 border-t border-[var(--pos-divider)] bg-[var(--pos-catalog)] p-2.5">{footer}</div> : null}</section>)
PosCatalog.displayName = "PosCatalog"

export interface PosSearchFieldProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange"> { value: string; onChange: (value: string) => void; onClear?: () => void; label: string; loading?: boolean; resultCount?: number }
export const PosSearchField = React.forwardRef<HTMLInputElement, PosSearchFieldProps>(({ className, label, loading, onChange, onClear, resultCount, value, ...props }, ref) => { const id = React.useId(); return <div className={cn("min-w-0", className)}><label htmlFor={id} className="mb-1 block text-xs font-medium text-[var(--dashboard-label)]">{label}</label><div className="relative"><Search aria-hidden="true" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--dashboard-muted)]"/><Input ref={ref} id={id} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 pl-10 pr-12 text-sm" aria-busy={loading || undefined} {...props}/>{value && onClear ? <button type="button" onClick={onClear} className="dashboard-focus-visible absolute right-1 top-1/2 flex size-11 -translate-y-1/2 items-center justify-center rounded-[var(--radius-dashboard-button)]" aria-label="Effacer la recherche"><X aria-hidden="true" className="size-4"/></button> : null}</div>{typeof resultCount === "number" ? <p className="mt-1 text-xs text-[var(--dashboard-muted)]" role="status">{resultCount} résultat{resultCount > 1 ? "s" : ""}</p> : null}</div> })
PosSearchField.displayName = "PosSearchField"

export interface PosCategoryRailProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> { items: PosCategoryPresentation[]; value?: string | null; onValueChange: (id: string) => void; ariaLabel?: string }
export const PosCategoryRail = React.forwardRef<HTMLDivElement, PosCategoryRailProps>(({ ariaLabel = "Catégories", className, items, onValueChange, value, ...props }, ref) => <div ref={ref} role="group" aria-label={ariaLabel} className={cn("flex max-w-full gap-2 overflow-x-auto pb-1", className)} {...props}>{items.map((item) => <button key={item.id} type="button" disabled={item.disabled} aria-pressed={value === item.id} onClick={() => onValueChange(item.id)} className={cn("dashboard-focus-visible flex min-h-11 shrink-0 items-center gap-2 rounded-full border px-3 text-sm font-semibold", value === item.id ? "border-[var(--brand-primary)] bg-[var(--brand-primary)] text-[var(--action-primary-fg)]" : "border-[var(--pos-border)] bg-[var(--pos-panel)]", "disabled:cursor-not-allowed disabled:opacity-50")}>{item.imageUrl ? <img src={item.imageUrl} alt="" className="size-7 rounded-full object-cover"/> : null}<span>{item.label}</span>{typeof item.count === "number" ? <span aria-label={`${item.count} produits`} className="tabular-nums opacity-75">{item.count}</span> : null}</button>)}</div>)
PosCategoryRail.displayName = "PosCategoryRail"

export interface PosProductGridProps extends React.HTMLAttributes<HTMLDivElement> { layout?: "oneColumn" | "twoColumns" | "adaptive" | "dense" }
export const PosProductGrid = React.forwardRef<HTMLDivElement, PosProductGridProps>(({ className, layout = "adaptive", ...props }, ref) => <div ref={ref} className={cn("grid min-w-0 gap-3", layout === "oneColumn" && "grid-cols-1", layout === "twoColumns" && "grid-cols-2", layout === "adaptive" && "grid-cols-1 min-[360px]:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5", layout === "dense" && "grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5", className)} {...props}/>)
PosProductGrid.displayName = "PosProductGrid"
