import * as React from "react"
import { AlertCircle, CheckCircle2, Clock3, PauseCircle, XCircle } from "lucide-react"
import { cn } from "@/lib/utils"
import type { PosSessionDisplayStatus } from "./pos-foundations"

const tones: Record<PosSessionDisplayStatus, string> = { closed: "bg-[var(--pos-session-closed-bg)] text-[var(--pos-session-closed-fg)]", opening: "bg-[var(--pos-session-validation-bg)] text-[var(--pos-session-validation-fg)]", active: "bg-[var(--pos-session-active-bg)] text-[var(--pos-session-active-fg)]", paused: "bg-[var(--pos-session-paused-bg)] text-[var(--pos-session-paused-fg)]", closing: "bg-[var(--pos-session-closing-bg)] text-[var(--pos-session-closing-fg)]", pendingValidation: "bg-[var(--pos-session-validation-bg)] text-[var(--pos-session-validation-fg)]", validated: "bg-[var(--pos-session-active-bg)] text-[var(--pos-session-active-fg)]", error: "bg-[var(--pos-session-error-bg)] text-[var(--pos-session-error-fg)]", unknown: "bg-[var(--pos-muted)] text-[var(--dashboard-muted)]" }
const icons: Record<PosSessionDisplayStatus, React.ReactNode> = { closed: <XCircle />, opening: <Clock3 />, active: <CheckCircle2 />, paused: <PauseCircle />, closing: <Clock3 />, pendingValidation: <Clock3 />, validated: <CheckCircle2 />, error: <AlertCircle />, unknown: <AlertCircle /> }
export interface PosSessionStatusProps extends React.HTMLAttributes<HTMLDivElement> { status: PosSessionDisplayStatus; label: React.ReactNode; description?: React.ReactNode; openedAt?: React.ReactNode; openedBy?: React.ReactNode; openingAmount?: React.ReactNode; compact?: boolean }
export const PosSessionStatus = React.forwardRef<HTMLDivElement, PosSessionStatusProps>(({ className, compact = false, description, label, openedAt, openedBy, openingAmount, status, ...props }, ref) => <div ref={ref} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] p-3", tones[status], compact && "p-2", className)} {...props}><div className="flex items-start gap-2"><span aria-hidden="true" className="mt-0.5 shrink-0 [&_svg]:size-5">{icons[status]}</span><div className="min-w-0"><p className="text-sm font-semibold">{label}</p>{description ? <p className="text-xs opacity-90">{description}</p> : null}{openedAt || openedBy || openingAmount ? <dl className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs">{openedAt ? <div><dt className="sr-only">Ouverture</dt><dd>{openedAt}</dd></div> : null}{openedBy ? <div><dt className="sr-only">Ouverte par</dt><dd>{openedBy}</dd></div> : null}{openingAmount ? <div><dt className="sr-only">Montant d'ouverture</dt><dd className="font-semibold tabular-nums">{openingAmount}</dd></div> : null}</dl> : null}</div></div></div>)
PosSessionStatus.displayName = "PosSessionStatus"

