import * as React from "react"
import { Minus, Plus, Trash2 } from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

export interface PosCartProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> { title?: React.ReactNode; itemCount?: React.ReactNode; totals?: React.ReactNode; actions?: React.ReactNode; emptyState?: React.ReactNode; loading?: boolean; hideHeader?: boolean }
export const PosCart = React.forwardRef<HTMLElement, PosCartProps>(({ actions, children, className, emptyState, hideHeader = false, itemCount, loading, title = "Panier", totals, ...props }, ref) => <section ref={ref} aria-busy={loading || undefined} className={cn("flex h-full min-h-0 flex-col overflow-hidden rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-cart)] shadow-[var(--shadow-dashboard-floating)]", className)} {...props}>{hideHeader ? null : <header className="flex min-h-14 shrink-0 items-center justify-between gap-3 border-b border-[var(--pos-divider)] px-4"><h2 className="text-base font-semibold">{title}</h2>{itemCount !== undefined ? <span className="text-sm tabular-nums text-[var(--dashboard-muted)]">{itemCount}</span> : null}</header>}<div className="min-h-0 flex-1 overflow-y-auto p-3">{children ?? emptyState}</div>{totals || actions ? <footer className="shrink-0 border-t border-[var(--pos-divider)] bg-[var(--pos-elevated)] p-3 pb-[calc(.75rem+var(--safe-bottom,0px))]">{totals}{actions ? <div className="mt-3">{actions}</div> : null}</footer> : null}</section>)
PosCart.displayName = "PosCart"

export interface PosQuantityControlsProps extends React.HTMLAttributes<HTMLDivElement> { quantity: React.ReactNode; onIncrease?: () => void; onDecrease?: () => void; disabled?: boolean; minReached?: boolean; maxReached?: boolean; increaseLabel?: string; decreaseLabel?: string }
export const PosQuantityControls = React.forwardRef<HTMLDivElement, PosQuantityControlsProps>(({ className, decreaseLabel = "Diminuer la quantité", disabled, increaseLabel = "Augmenter la quantité", maxReached, minReached, onDecrease, onIncrease, quantity, ...props }, ref) => <div ref={ref} className={cn("inline-flex items-center gap-1", className)} {...props}><Button type="button" variant="outline" size="icon" className="size-11 shrink-0" disabled={disabled || minReached} onClick={onDecrease} aria-label={decreaseLabel}><Minus aria-hidden="true" className="size-4"/></Button><output aria-label="Quantité" className="flex min-h-11 min-w-11 items-center justify-center px-1 text-base font-bold tabular-nums">{quantity}</output><Button type="button" variant="outline" size="icon" className="size-11 shrink-0" disabled={disabled || maxReached} onClick={onIncrease} aria-label={increaseLabel}><Plus aria-hidden="true" className="size-4"/></Button></div>)
PosQuantityControls.displayName = "PosQuantityControls"

export interface PosCartLineProps extends React.HTMLAttributes<HTMLElement> { name: React.ReactNode; description?: React.ReactNode; image?: React.ReactNode; quantity: React.ReactNode; options?: React.ReactNode; notes?: React.ReactNode; unitPrice?: React.ReactNode; lineTotal: React.ReactNode; onIncrease?: () => void; onDecrease?: () => void; onRemove?: () => void; disabled?: boolean; loading?: boolean }
export const PosCartLine = React.forwardRef<HTMLElement, PosCartLineProps>(({ className, description, disabled, image, lineTotal, loading, name, notes, onDecrease, onIncrease, onRemove, options, quantity, unitPrice, ...props }, ref) => <article ref={ref} aria-busy={loading || undefined} className={cn("min-w-0 rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-panel)] p-3", className)} {...props}><div className="flex min-w-0 items-start gap-3">{image ? <div className="size-14 shrink-0 overflow-hidden rounded-lg border border-[var(--pos-border)] bg-[var(--pos-muted)]">{image}</div> : null}<div className="flex min-w-0 flex-1 items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-sm font-semibold">{name}</h3>{description ? <p className="mt-0.5 break-words text-xs text-[var(--dashboard-muted)]">{description}</p> : null}{options ? <div className="mt-1 break-words text-xs text-[var(--dashboard-subtitle)]">{options}</div> : null}{notes ? <div className="mt-1 break-words text-xs text-[var(--data-warning)]">{notes}</div> : null}</div><div className="shrink-0 text-right">{unitPrice ? <p className="text-xs tabular-nums text-[var(--dashboard-muted)]">{unitPrice}</p> : null}<p className="text-sm font-bold tabular-nums">{lineTotal}</p></div></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><PosQuantityControls quantity={quantity} onDecrease={onDecrease} onIncrease={onIncrease} disabled={disabled || loading}/>{onRemove ? <Button type="button" variant="ghost" className="min-h-11 px-3 text-[var(--data-negative)]" disabled={disabled || loading} onClick={onRemove}><Trash2 aria-hidden="true" className="mr-2 size-4"/>Supprimer</Button> : null}</div></article>)
PosCartLine.displayName = "PosCartLine"

export interface PosTotalLine { id: string; label: React.ReactNode; value: React.ReactNode }
export interface PosTotalsProps extends React.HTMLAttributes<HTMLDListElement> { subtotal?: React.ReactNode; discount?: React.ReactNode; tax?: React.ReactNode; fees?: React.ReactNode; total: React.ReactNode; currency?: React.ReactNode; lines?: PosTotalLine[] }
export const PosTotals = React.forwardRef<HTMLDListElement, PosTotalsProps>(({ className, currency, discount, fees, lines = [], subtotal, tax, total, ...props }, ref) => { const standard = [{ id: "subtotal", label: "Sous-total", value: subtotal }, { id: "discount", label: "Remise", value: discount }, { id: "tax", label: "Taxes", value: tax }, { id: "fees", label: "Frais", value: fees }].filter((line) => line.value !== undefined && line.value !== null); return <dl ref={ref} className={cn("space-y-2", className)} {...props}>{[...standard, ...lines].map((line) => <div key={line.id} className="flex items-baseline justify-between gap-4 text-sm"><dt className="text-[var(--dashboard-muted)]">{line.label}</dt><dd className="max-w-[60%] break-words text-right font-medium tabular-nums">{line.value}</dd></div>)}<div className="flex items-end justify-between gap-4 border-t border-[var(--pos-divider)] pt-3"><dt className="text-sm font-semibold">Total</dt><dd aria-label="Total à payer" className="max-w-[70%] break-words text-right text-[length:var(--text-pos-total)] font-bold leading-none tabular-nums">{total}{currency ? <span className="ml-1 text-sm">{currency}</span> : null}</dd></div></dl> })
PosTotals.displayName = "PosTotals"

export interface PosCheckoutActionProps extends React.ButtonHTMLAttributes<HTMLButtonElement> { label: React.ReactNode; amount?: React.ReactNode; loading?: boolean; onSelect?: () => void }
export const PosCheckoutAction = React.forwardRef<HTMLButtonElement, PosCheckoutActionProps>(({ amount, className, disabled, label, loading, onSelect, ...props }, ref) => <Button ref={ref} type="button" onClick={onSelect} disabled={disabled || loading} aria-busy={loading || undefined} className={cn("min-h-14 w-full text-sm font-semibold", className)} {...props}><span>{loading ? "Traitement…" : label}</span>{amount !== undefined ? <span className="ml-auto tabular-nums">{amount}</span> : null}</Button>)
PosCheckoutAction.displayName = "PosCheckoutAction"
