import * as React from "react"
import { cn } from "@/lib/utils"
import type { PosLayoutMode, PosSessionDisplayStatus } from "./pos-foundations"
import { PosSessionStatus } from "./pos-session"

export interface PosPageProps extends React.HTMLAttributes<HTMLElement> { header?: React.ReactNode; layout?: PosLayoutMode; fullHeight?: boolean; withGutters?: boolean; touchMode?: boolean }
export const PosPage = React.forwardRef<HTMLElement, PosPageProps>(({ children, className, fullHeight = true, header, layout = "adaptive", touchMode = false, withGutters = true, ...props }, ref) => <main ref={ref} data-pos-layout={layout} data-pos-touch={touchMode || undefined} className={cn("dashboard-reduced-motion flex min-h-[100dvh] min-w-0 flex-col overflow-x-hidden bg-[var(--pos-canvas)] font-[var(--font-dashboard)] text-[var(--dashboard-title)]", fullHeight && "h-[100dvh] overflow-hidden", className)} {...props}>{header}<div className={cn("min-h-0 min-w-0 flex-1", withGutters && "px-[calc(var(--pos-gutter-x)+var(--safe-left,0px))] pb-[calc(var(--pos-gutter-y)+var(--safe-bottom,0px))] pt-[var(--pos-gutter-y)] pr-[calc(var(--pos-gutter-x)+var(--safe-right,0px))]", fullHeight && "overflow-hidden")}>{children}</div></main>)
PosPage.displayName = "PosPage"

export interface PosHeaderProps extends Omit<React.HTMLAttributes<HTMLElement>, "title"> { title: React.ReactNode; user?: React.ReactNode; workstation?: React.ReactNode; sessionStatus?: PosSessionDisplayStatus; sessionLabel?: React.ReactNode; duration?: React.ReactNode; openingAmount?: React.ReactNode; actions?: React.ReactNode; closeSessionAction?: React.ReactNode; reportAction?: React.ReactNode; fullScreenAction?: React.ReactNode }
export const PosHeader = React.forwardRef<HTMLElement, PosHeaderProps>(({ actions, className, closeSessionAction, duration, fullScreenAction, openingAmount, reportAction, sessionLabel, sessionStatus, title, user, workstation, ...props }, ref) => <header ref={ref} className={cn("shrink-0 border-b border-[var(--pos-divider)] bg-[var(--pos-panel)] px-[calc(var(--pos-gutter-x)+var(--safe-left,0px))] pb-3 pt-[calc(.75rem+var(--safe-top,0px))] pr-[calc(var(--pos-gutter-x)+var(--safe-right,0px))] shadow-[var(--shadow-dashboard-surface)]", className)} {...props}><div className="flex min-w-0 flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h1 className="break-words text-[length:var(--text-pos-page-title)] font-bold leading-tight">{title}</h1>{user || workstation ? <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[var(--dashboard-muted)]">{user}{workstation}</div> : null}</div>{sessionStatus || sessionLabel || duration || openingAmount ? <PosSessionStatus status={sessionStatus ?? "unknown"} label={sessionLabel ?? "Session"} description={duration} openingAmount={openingAmount} compact /> : null}<div className="flex flex-wrap items-center gap-2 [&_button]:min-h-11 [&_button]:min-w-11">{actions}{reportAction}{fullScreenAction}{closeSessionAction}</div></div></header>)
PosHeader.displayName = "PosHeader"

export interface PosLayoutProps extends React.HTMLAttributes<HTMLDivElement> { catalog: React.ReactNode; cart: React.ReactNode; aside?: React.ReactNode; layout?: PosLayoutMode }
export const PosLayout = React.forwardRef<HTMLDivElement, PosLayoutProps>(({ aside, cart, catalog, className, layout = "adaptive", ...props }, ref) => <div ref={ref} data-layout={layout} className={cn("grid h-full min-h-0 min-w-0 gap-[var(--pos-layout-gap)]", layout === "stack" && "grid-cols-1 overflow-y-auto", layout === "split" && "grid-cols-[minmax(0,1fr)_minmax(20rem,var(--pos-cart-width))]", layout === "adaptive" && "grid-cols-1 overflow-y-auto lg:grid-cols-[minmax(0,1fr)_minmax(20rem,var(--pos-cart-width))] lg:overflow-hidden", aside && "xl:grid-cols-[minmax(0,1fr)_minmax(20rem,var(--pos-cart-width))_minmax(16rem,var(--pos-aside-width))]", className)} {...props}><section className="min-h-0 min-w-0">{catalog}</section><aside className="min-h-0 min-w-0">{cart}</aside>{aside ? <aside className="min-h-0 min-w-0">{aside}</aside> : null}</div>)
PosLayout.displayName = "PosLayout"

