"use client"
import * as React from "react"
import { Banknote, Smartphone } from "lucide-react"
import { cn } from "@/lib/utils"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import type { PosMobileProviderPresentation, PosPaymentDisplayMethod } from "./pos-foundations"

export interface PosPaymentDialogProps { open: boolean; onOpenChange: (open: boolean) => void; title: React.ReactNode; description?: React.ReactNode; total: React.ReactNode; children?: React.ReactNode; footer?: React.ReactNode; initialFocusRef?: React.RefObject<HTMLElement | null>; compact?: boolean; className?: string; error?: React.ReactNode }
export function PosPaymentDialog({ children, className, compact = false, description, error, footer, initialFocusRef, onOpenChange, open, title, total }: PosPaymentDialogProps) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent onOpenAutoFocus={(event) => { if (initialFocusRef?.current) { event.preventDefault(); initialFocusRef.current.focus() } }} className={cn("max-h-[calc(100dvh-var(--safe-top,0px)-var(--safe-bottom,0px)-1rem)] max-w-2xl overflow-y-auto rounded-[var(--radius-dashboard-overlay)] border border-[var(--pos-border)] bg-[var(--pos-elevated)]", className)}><DialogHeader className={cn(compact && "space-y-0")}><DialogTitle>{title}</DialogTitle>{description ? <DialogDescription className={cn(compact && "[@media(max-height:800px)]:hidden")}>{description}</DialogDescription> : null}</DialogHeader><div className={cn("rounded-[var(--radius-dashboard-widget)] bg-[var(--pos-muted)] p-3", compact && "flex items-center justify-between gap-3 p-2.5")}><p className="text-xs text-[var(--dashboard-muted)]">Total à payer</p><p className={cn("break-words text-[length:var(--text-pos-total)] font-bold tabular-nums", compact && "text-xl")}>{total}</p></div>{children}{error ? <div role="alert" className="rounded-[var(--radius-dashboard-widget)] bg-[var(--pos-payment-failed-bg)] p-3 text-sm text-[var(--pos-payment-failed-fg)]">{error}</div> : null}{footer ? <DialogFooter>{footer}</DialogFooter> : null}</DialogContent></Dialog> }

export interface PosPaymentMethodChoiceProps extends React.HTMLAttributes<HTMLDivElement> { method: PosPaymentDisplayMethod; label: React.ReactNode; description?: React.ReactNode; selected?: boolean; disabled?: boolean; compact?: boolean; onSelect?: () => void; icon?: React.ReactNode; logo?: React.ReactNode }
export const PosPaymentMethodChoice = React.forwardRef<HTMLDivElement, PosPaymentMethodChoiceProps>(({ className, compact = false, description, disabled, icon, label, logo, method, onSelect, selected, ...props }, ref) => <div ref={ref} className={cn("relative", className)} {...props}><label className={cn("flex min-h-14 cursor-pointer items-center gap-3 rounded-[var(--radius-dashboard-widget)] border bg-[var(--pos-panel)] p-3", compact && "min-h-12 p-2.5", selected ? "border-[var(--brand-primary)]" : "border-[var(--pos-border)]", disabled && "cursor-not-allowed opacity-50")}><input type="radio" name="pos-payment-method" value={method} checked={Boolean(selected)} disabled={disabled} onChange={() => onSelect?.()} className="size-4 accent-[var(--brand-primary)]"/><span aria-hidden="true" className="[&_svg]:size-5">{logo ?? icon ?? (method === "cash" ? <Banknote/> : <Smartphone/>)}</span><span className="min-w-0"><span className="block text-sm font-semibold">{label}</span>{description ? <span className={cn("block text-xs text-[var(--dashboard-muted)]", compact && "[@media(max-height:740px)]:hidden")}>{description}</span> : null}</span></label></div>)
PosPaymentMethodChoice.displayName = "PosPaymentMethodChoice"

export interface PosCashPaymentProps extends React.HTMLAttributes<HTMLDivElement> { expectedAmount: React.ReactNode; receivedValue: string; onReceivedChange: (value: string) => void; changeAmount?: React.ReactNode; error?: React.ReactNode; disabled?: boolean; loading?: boolean; quickAmounts?: Array<{ id: string; label: React.ReactNode; value: string }>; onQuickAmount?: (value: string) => void }
export const PosCashPayment = React.forwardRef<HTMLDivElement, PosCashPaymentProps>(({ changeAmount, className, disabled, error, expectedAmount, loading, onQuickAmount, onReceivedChange, quickAmounts = [], receivedValue, ...props }, ref) => { const id = React.useId(); const errorId = `${id}-error`; return <div ref={ref} className={cn("space-y-4", className)} {...props}><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-[var(--dashboard-muted)]">Montant attendu</dt><dd className="break-words text-xl font-bold tabular-nums">{expectedAmount}</dd></div>{changeAmount !== undefined ? <div><dt className="text-xs text-[var(--dashboard-muted)]">Monnaie à rendre</dt><dd className="break-words text-xl font-bold tabular-nums">{changeAmount}</dd></div> : null}</dl><div><Label htmlFor={id}>Montant reçu</Label><Input id={id} value={receivedValue} onChange={(event) => onReceivedChange(event.target.value)} disabled={disabled || loading} inputMode="numeric" className="mt-1 min-h-12 text-lg font-semibold tabular-nums" aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined}/>{error ? <p id={errorId} role="alert" className="mt-1 text-sm text-[var(--data-negative)]">{error}</p> : null}</div>{quickAmounts.length ? <div className="flex flex-wrap gap-2">{quickAmounts.map((amount) => <button key={amount.id} type="button" disabled={disabled || loading} onClick={() => onQuickAmount?.(amount.value)} className="dashboard-focus-visible min-h-11 rounded-[var(--radius-dashboard-button)] border border-[var(--pos-border)] px-3 text-sm font-semibold tabular-nums">{amount.label}</button>)}</div> : null}</div> })
PosCashPayment.displayName = "PosCashPayment"

export interface PosMobileMoneyPaymentProps extends React.HTMLAttributes<HTMLDivElement> { providers: PosMobileProviderPresentation[]; selectedProvider?: string | null; onProviderChange: (id: string) => void; phone?: string; onPhoneChange?: (value: string) => void; reference?: string; onReferenceChange?: (value: string) => void; instructions?: React.ReactNode; error?: React.ReactNode; disabled?: boolean; loading?: boolean }
export const PosMobileMoneyPayment = React.forwardRef<HTMLDivElement, PosMobileMoneyPaymentProps>(({ className, disabled, error, instructions, loading, onPhoneChange, onProviderChange, onReferenceChange, phone, providers, reference, selectedProvider, ...props }, ref) => { const phoneId = React.useId(); const refId = React.useId(); return <div ref={ref} className={cn("space-y-4", className)} {...props}><RadioGroup value={selectedProvider ?? undefined} onValueChange={onProviderChange} disabled={disabled || loading} aria-label="Opérateur Mobile Money">{providers.map((provider) => <label key={provider.id} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-panel)] p-3"><RadioGroupItem value={provider.id}/>{provider.logo}<span><span className="block text-sm font-semibold">{provider.label}</span>{provider.description ? <span className="block text-xs text-[var(--dashboard-muted)]">{provider.description}</span> : null}</span></label>)}</RadioGroup>{onPhoneChange ? <div><Label htmlFor={phoneId}>Téléphone</Label><Input id={phoneId} value={phone ?? ""} onChange={(event) => onPhoneChange(event.target.value)} disabled={disabled || loading} inputMode="tel" className="mt-1 min-h-12"/></div> : null}{onReferenceChange ? <div><Label htmlFor={refId}>Référence</Label><Input id={refId} value={reference ?? ""} onChange={(event) => onReferenceChange(event.target.value)} disabled={disabled || loading} className="mt-1 min-h-12"/></div> : null}{instructions ? <div className="rounded-[var(--radius-dashboard-widget)] bg-[var(--pos-muted)] p-3 text-sm">{instructions}</div> : null}{error ? <p role="alert" className="text-sm text-[var(--data-negative)]">{error}</p> : null}</div> })
PosMobileMoneyPayment.displayName = "PosMobileMoneyPayment"
