"use client"
import * as React from "react"
import { cn } from "@/lib/utils"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import type { PosClosingVarianceState } from "./pos-foundations"

const varianceClasses: Record<PosClosingVarianceState, string> = { balanced: "bg-[var(--pos-variance-balanced-bg)] text-[var(--pos-variance-balanced-fg)]", positive: "bg-[var(--pos-variance-positive-bg)] text-[var(--pos-variance-positive-fg)]", negative: "bg-[var(--pos-variance-negative-bg)] text-[var(--pos-variance-negative-fg)]", warning: "bg-[var(--pos-variance-warning-bg)] text-[var(--pos-variance-warning-fg)]", unknown: "bg-[var(--pos-muted)] text-[var(--dashboard-muted)]" }
export interface PosVarianceDisplayProps extends React.HTMLAttributes<HTMLDListElement> { expected: React.ReactNode; received: React.ReactNode; variance: React.ReactNode; state: PosClosingVarianceState; label: React.ReactNode }
export const PosVarianceDisplay = React.forwardRef<HTMLDListElement, PosVarianceDisplayProps>(({ className, expected, label, received, state, variance, ...props }, ref) => <dl ref={ref} className={cn("rounded-[var(--radius-dashboard-widget)] p-3", varianceClasses[state], className)} {...props}><div className="mb-2 font-semibold">{label}</div><div className="grid grid-cols-1 gap-2 text-sm sm:grid-cols-3"><div><dt>Attendu</dt><dd className="font-semibold tabular-nums">{expected}</dd></div><div><dt>Déclaré</dt><dd className="font-semibold tabular-nums">{received}</dd></div><div><dt>Écart</dt><dd className="font-bold tabular-nums">{variance}</dd></div></div></dl>)
PosVarianceDisplay.displayName = "PosVarianceDisplay"

interface ControlledDialogProps { open: boolean; onOpenChange: (open: boolean) => void; title: React.ReactNode; description?: React.ReactNode; children?: React.ReactNode; footer?: React.ReactNode; error?: React.ReactNode; className?: string }
function SessionDialog({ children, className, description, error, footer, onOpenChange, open, title }: ControlledDialogProps) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className={cn("max-h-[calc(100dvh-var(--safe-top,0px)-var(--safe-bottom,0px)-1rem)] max-w-2xl overflow-y-auto rounded-[var(--radius-dashboard-overlay)]", className)}><DialogHeader><DialogTitle>{title}</DialogTitle>{description ? <DialogDescription>{description}</DialogDescription> : null}</DialogHeader>{children}{error ? <div role="alert" className="rounded-md bg-[var(--pos-session-error-bg)] p-3 text-sm text-[var(--pos-session-error-fg)]">{error}</div> : null}{footer ? <DialogFooter>{footer}</DialogFooter> : null}</DialogContent></Dialog> }
export interface PosSessionOpeningDialogProps extends ControlledDialogProps { workstation?: React.ReactNode; user?: React.ReactNode; openingAmount?: React.ReactNode; date?: React.ReactNode }
export function PosSessionOpeningDialog({ date, openingAmount, user, workstation, children, ...props }: PosSessionOpeningDialogProps) { return <SessionDialog {...props}><dl className="grid gap-3 rounded-[var(--radius-dashboard-widget)] bg-[var(--pos-muted)] p-3 sm:grid-cols-2">{workstation ? <div><dt className="text-xs text-[var(--dashboard-muted)]">Poste</dt><dd>{workstation}</dd></div> : null}{user ? <div><dt className="text-xs text-[var(--dashboard-muted)]">Utilisateur</dt><dd>{user}</dd></div> : null}{openingAmount ? <div><dt className="text-xs text-[var(--dashboard-muted)]">Montant initial</dt><dd className="font-semibold tabular-nums">{openingAmount}</dd></div> : null}{date ? <div><dt className="text-xs text-[var(--dashboard-muted)]">Date</dt><dd>{date}</dd></div> : null}</dl>{children}</SessionDialog> }
export interface PosSessionClosingDialogProps extends ControlledDialogProps { summary?: React.ReactNode; expectedCash?: React.ReactNode; declaredCash?: React.ReactNode; mobileMoney?: React.ReactNode; otherValues?: React.ReactNode; variance?: React.ReactNode; justification?: React.ReactNode; confirmation?: React.ReactNode }
export function PosSessionClosingDialog({ confirmation, declaredCash, expectedCash, justification, mobileMoney, otherValues, summary, variance, ...props }: PosSessionClosingDialogProps) { return <SessionDialog {...props}>{summary}<div className="grid gap-3 sm:grid-cols-2">{expectedCash}{declaredCash}{mobileMoney}{otherValues}</div>{variance}{justification}{confirmation}</SessionDialog> }

export interface PosSessionReportProps extends React.HTMLAttributes<HTMLElement> { session: React.ReactNode; user?: React.ReactNode; schedule?: React.ReactNode; sales?: React.ReactNode; cash?: React.ReactNode; mobileMoney?: React.ReactNode; cancellations?: React.ReactNode; discounts?: React.ReactNode; variances?: React.ReactNode; printAction?: React.ReactNode; exportAction?: React.ReactNode }
export const PosSessionReport = React.forwardRef<HTMLElement, PosSessionReportProps>(({ cancellations, cash, className, discounts, exportAction, mobileMoney, printAction, sales, schedule, session, user, variances, ...props }, ref) => <article ref={ref} className={cn("rounded-[var(--radius-dashboard-widget)] border border-[var(--pos-border)] bg-[var(--pos-panel)] p-4", className)} {...props}><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Rapport de session</h2><div className="mt-1 text-sm text-[var(--dashboard-muted)]">{session}{user}{schedule}</div></div><div className="flex gap-2 [&_button]:min-h-11">{printAction}{exportAction}</div></header><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sales}{cash}{mobileMoney}{cancellations}{discounts}{variances}</div></article>)
PosSessionReport.displayName = "PosSessionReport"

